Meridian59/Meridian59

kod/object/active/holder/nomoveon/battler/player.kod

This is how we fixed the bug on 103 causing players to be unable to rescue/elusion. The piTimeAttackedPlayer property needs to be set to current time with other properties in UpdateTimeValues so when the system time is larger than the KOD integer limit and is reset, it can be set to the new lower time value.
Running send c player UpdateTimeValues after this code is live will fix the bug for all players (after the requisite time has passed).

Allow UpdateTimeValues to reset piTimeAttackedPlayer.

---

kod/object/active/holder/nomoveon/battler/player.kod

This is a change that went into 103, after an HP is basically fills vigor and sets HP's to their (new) max. It's based on the idea that building is a massive grind and it's a little pep-in-your-step to be rewarded with full vigor and max hp.
Mayhem requested I submit it to official servers.

Invigorate after HP.

---

club/makefile

Since we are no longer using wrap I do not know why it is still in here and archive.lib is not. Generates errors when trying to compile the source if wrap.lib is in.

Remove wrap.lib

---

clientd3d/makefile

Remove mss32.lib and mss32midi.lib, trying to compile with these two libs added will generate error when trying to compile the source.

Remove missing libs

---

roomedit/windeu.ini

The folders name is 'localclient' not 'client'.

Corrected the location of the client folder

---

kod/object/active/holder/room.kod

Popular requests to re-enable webs and spores in doors have been
intense, to say the least, predicated on the basis that they do not deal
damage and can't be used to kill newbies in a cheesy fashion. They are
also very important for crowd control, and best used in doors
specifically. It is, in fact, not that people zone into them and get stuck,
but rather that they don't enter the room at all because of the trap wall.
That strategic element of blocking entrances doesn't translate when used
away from the door.
This pull excludes webs and active & passive spores from deletion by
the room entrance code.

Allow non-damage walls in doors

---

kod/object/active/holder/nomoveon/battler/monster/eviltwin.kod
kod/object/active/holder/nomoveon/battler/monster/reflectn.kod

Originaly by MorbusM59
Reflections and evil twins were only correctly using bow animations when the owner was using a long bow. This allows the copies to use the correct animation for all bows.

Little fix for ET/Reflection animations 

---

kod/object/item/passitem/attmod/gauntlet.kod

Gauntlets didn't update their own graphic when they broke due to strange
DefendingHit code overwriting item.kod's gear-breaking code. This fixes
that issue, so gauntlets will appear broken in one's inventory
appropriately.

Fixed Gauntlets breaking behavior

---

kod/object/passive/brain.kod
kod/util/settings.kod

The 3 aggro limit is caused by not having monsters check if they're being attacked before cancelling hatred due to the amount of monsters already chasing the attacker.
This change adds a check for TS_FIGHT_ME_VICTIM before hatred is reduced, so that if a player attacks a monster, it will aggro no matter what (i.e. no more monsters sitting around letting themselves be killed).
Fixed up the spacing around the area I edited a little.

Fix 3 aggro limit - check if player attacked monster.

---

kod/object/active/holder/nomoveon/battler/monster/ent.kod
kod/object/active/holder/nomoveon/battler/monster/evilent.kod

Without this change, based on kod/object/passive/body.kod, the dead description of a tree would be...
"This is a dead, decompossing dead remains of diseased tree..."

Fix Dead Tree Description for Superclass Override

---

blakserv/ccode.c

Some of the string terminations in StringSubstitute were being placed 1 char ahead of the correct position, leading to incorrect string lengths.
I left out the formatting changes/cleanup so the functional changes could be seen, if you like I can add the other changes from https://github.com/OpenMeridian105/Meridian59/commit/527efa8f19471236158cd7783c7a543c9af6ca46

Fix StringSubstitute errors.

---

blakserv/osd_linux.c
blakserv/osd_linux.h

ignore SIGPIPE "crash" caused when calling send() on a closed socket

---

kod/object/active/holder/nomoveon/battler/player.kod
kod/util/settings.kod

(Resolved issues with previous  pull request)
While the cost to broadcast can be useful to prevent flame wars and spamming, it also reduces player ability to ask questions and socialize. (Puts a damper on trivia contests too!) This value can be changed to tweak the penalty in real time by an admin

Made broadcast mana penalty a setting that can be changed at runtime

---

kod/object/active/holder/room/temprii.kod

Riija Temple bridge is coded to sometimes drop an item when the player falls. However, it checks if an item is valid to drop with ReqLeaveOwner, which is only ever false for cursed items. Here I've added a check for DropOnDeath, which will exclude very important items like room keys and bonded equipment.

Fix Riija Bridge overzealous item dropping

---

kod/object/item/passitem/weapon.kod
kod/object/item/passitem/weapon/goldswrd.kod

Nerudite Arrows haven't been shattering because BaseDamage wasn't
passing who and target. Silver Arrows also weren't doing double damage
to undead.

Ammo fix Nerudite/Silver Arrows

---

kod/object/passive/spell/roomench/light.kod

_A re-submission of #387 because I had to modify my local branches._
This updates Faren's Light sfx by updating its reference from `flight.wav`, a sfx that quite possibly doesn't exist, to`faren.wav`. It is in response to #224.
After installing and looking through the resources for the only two discs I could installed (Insurrection and Dark Auspices) I was unable to find `flight.wav` or equivalent sound under a different name. I created a potential new sfx that I'll share below, but ultimately chose to do what spells like Bramble and Lightning Wall do: use `faren.wav`. The generic Faren sfx might be one of the better choices considering how frequently a spell like Light might be cast (i.e. less noise, relatively speaking).
Here is the result: …

Update light to use generic Faren sfx

---

kod/object/item/passitem/ring/ringwedd.kod

The wedding ring is more a roleplayitem and was rarely used by the players, cause nobody knew about the defense boon before the game went open source. The item is simple overpowered on casters or hybrid-toons, with high agility, robe and cess-faction. Even a Purefighter will allways miss the caster/hybrid-toon over the half of the time.
Otherwise we had to create a perma "war-ring" which gives the same boon on offense.

Reblance: Wedding Ring

---

kod/object/passive/itematt/weapatt/wavamper.kod

I did never understand why hold/blind/purge weapons have no karma requirements but vampiric weapons have.
Without it they would be great building weapons!

Removed Karma requirement from VampWeaponAttribute

---

kod/util/rntmaint.kod

This PR would close #382, which asks that the maximum length at which rooms can be rented be moved from a constant to a property that can be managed by an administrator with a deeper understanding of the state of the server.
To test this, I logged in as an administrator, found the `RentableRoomMaintenance` instance and updated `piRentableDaysMax` from `240` to `365`. I then executed a system save and confirmed that the property value was still `365`.
cc @qorkod

Make rented room duration maximum editable by admins

---

kod/object/active/holder/nomoveon/battler/player.kod

This commit fixes a comparison bug in #300. Plain and simple.

Fixes a comparison bug in `player.kod`, which leads to a compilation error

---

kod/object/active/holder/room/monsroom/guest6.kod

This commit closes #402 by reducing the range of the Raza Mausoleum's monster check by 1 grid row. Currently, the logic reaches into row 27, which is the grid square the right lever sits in (see image below). It should not be included and since it is, a monster present in that square will block the final room from finishing. With this PR, the check extends to row 26.
It was brought to my attention that a mummy had made its way behind the lever and as a result, the column in the final room wouldn't drop. I was able to reproduce this locally by teleporting a mummy to ROW 27, COL 4 and confirmed that when the final room was cleared, the column dropped and the room reset as expected.
The rows and columns currently checked for monsters:

Remove lever area from monster check

---

kod/object/active/holder/room/monsroom/guest6.kod

This commit fixes #381 by removing a questionable bit of logic increasing the max monster count of the room by 1 each time the door slam timer is executed. The issue was resulting in an ever-increasing number of monsters in the room (in the hundreds).
Although this change now maintains the max monster count (20), the room's need to spawn 5 pit mummies means that max monster count will often be exceeded if close to 20 monsters are present elsewhere in the Mausoleum. For example, if you complete the pit and it resets while there are 18 monsters elsewhere, the pit will reset and there will be 23 monsters. The room should not exceed 25 monsters.
To test this locally I had to `SLAM_TIME = 2000` to `SLAM_TIME = 5000`, to give myself enough time to pull both levers and access the pit. I killed …

Fixes Mausoleum max monster count issue

---

kod/object/active/holder/nomoveon/battler/player.kod
kod/object/passive/skill/secwind.kod

This PR builds on the work of @skittles1 and @Nagath in #296 and closes #296 if merged.
As it stands today, Second Wind does not trigger a visual indicator and #296 adds one with a few minor bugs this PR initially addressed. Per the suggestion of @Meridian59, I've pivoted this PR to refactor second wind to mimic personal enchantment spells. No changes to the core second wind functionality should be changed by this PR.
- The original handling of second wind updates the player's rest threshold from 80 to >80 once second wind dissipates. I don't understand why and it seems like it could be a bug, because I don't see anything that says second wind should permanently affect a player's default rest threshold.
* Testing requires your player to to be in several states (i.e. vigor below threshold, …

Update second wind enchantment

---

module/mailnews/mailnews.rc
module/mailnews/newsread.c

This PR targets part #26 by updating the news globe dialog to have sortable columns.
My solution was to implement a list comparison callback on column click. The sort used was unstable, hence the addition of the article number for stability. This is not an area I have much experience in, so whether or not this is performant in the face of large data sets is unknown to me (and I expect there to be large datasets).
* My test data is _very_ minimal; only about a dozen list items

Unlock and add newsgroup sorting functionality

---

module/mailnews/mailnews.rc
module/mailnews/newsread.c

Reverts Meridian59/Meridian59#398
I found a few problems when I tested this locally:
- Clicking on an article in the top half doesn't load the article content into the bottom half.
- Clicking on a header sometimes sorts that column, but sometimes it does nothing, and sometimes it appears to sort a different column.

Revert "Unlock and add newsgroup sorting functionality"

---

kod/object/item/passitem/ring/ringwedd.kod

The implementation of #194 is causing issues due to the absence of handlers for ModifyDefensePower and ModifyDefenseDamage. This commit brings back those handlers and passes through the defense power and damage values in the DefMod calls on the wedding ring, rendering any sort of DefMod properties meaningless.

Negates the DefMod calls being made on wedding rings

---

module/merintr/mermain.c
module/merintr/statmain.c

Players main stat icons (such as mana, vigour and health) and graph background are missing and often not visible when first logging in to the game.
Moving to a new screen or resizing the window refreshes these icons.
To fix this issue we redraw the icons whenever stats are received from the server.

Fix missing main stat icons on login

---

kod/object/active/holder/nomoveon/battler/player.kod
kod/object/passive/skill/secwind.kod

This PR fixes an issue where Second Wind appears to work as intended, but does not improve.
As a subclass of `Skill`, Second Wind should override and pass control back to `DoSkill`, where skill advancement is handled. When SW was refactored recently, `DoSkill` was renamed to `TrySkill` and in doing so, had it's advancement handling cut off. This PR renames the method, propagates control to `Skill` and updates the handler call in `Player` to use the new handler name.
To test, I created an admin player, then gave it all spells and second wind at 1%. I also played around with the server advancement rate while testing, first at 9999 to force an improvement and then at the default of 100 to see that improvements were only taking place some of the time. I triggered SW 10+ times at an …

Fix second wind handler name

---

kod/object/active/holder/nomoveon/battler/player.kod
kod/object/passive/skill/secwind.kod

This PR resolves some outstanding issues with recent Second Wind changes and includes some refactoring:
1. It hooks Second Wind into Skill advancement, so that SW advancement is in line with overall `Skill` advancement. Under the current conditions, SW improvements are unlikely.
2. It implements `RemoveEnchantmentEffects` -- a handler for personal enchantments -- that was seen throwing missing handlers errors. This is a minor issue and was the result of our testing using the admin command, `RemoveAllEnchantments`.
3. It refactors SW code from `NewVigor()` into `AddExertion()`, as it seemed more appropriate to handle SW when adding exertion, not setting a new vigor value.
4. It refactors `EndEnchantmentEffects` into `EndEnchantment` for the sake of readability.
There's quite a bit to …

Fixes for Second Wind

---

kod/object/active/holder/room/ghall.kod

This commit re-enables previously removed logic and now allows allied guild members above the rank of Initiate to enter a guild hall. The code change was made back in 2013 in #163 at a time when I'm sure the community was a bit different, but there's been conversation about bringing it back.
My personal opinion is that the community ought to be able to police themselves on this one.

Allows guild allies to enter guild hall

---

clientd3d/animate.c
clientd3d/animate.h
clientd3d/config.c
clientd3d/config.h
clientd3d/draw3d.c
clientd3d/effect.c
clientd3d/game.c
clientd3d/map.c
clientd3d/meridian.ini
clientd3d/move.c
clientd3d/moveobj.c
clientd3d/overlay.c
clientd3d/project.c
clientd3d/roomanim.c
clientd3d/statgame.c
module/merintr/merintr.c

This PR:
- Removes code that slows down animations when the game is backgrounded
- Speeds up animations when dialogs are open to match non-dialog animations speeds
- Removes code for handling a config option related to animations that is no longer necessary.
Because the config option logic touches on lots of animations, I tested and validated the following:
* Guild hall doors animate as expected
* Blurry, wavering vision when drunk
* Animated sandstorm "dibs"
* POV shakes with earthquake cast
* Zooming the map in and out is smooth
* Firewalls animate
* Movement is slowed while walking through water
* Fireballs and lightning bolts animate towards their target
* Animations when going up or falling down vertically are present and consistent with production
* Animations are "smooth" and …

Removes handling of animate as a config option

---

kod/object/item/passitem/spelitem/potion/anonp.kod
kod/object/item/passitem/spelitem/potion/baitp.kod
kod/object/item/passitem/spelitem/potion/cloakp.kod
kod/object/item/passitem/spelitem/potion/curedisp.kod
kod/object/item/passitem/spelitem/potion/curepsnp.kod
kod/object/item/passitem/spelitem/potion/deflectp.kod
kod/object/item/passitem/spelitem/potion/detevilp.kod
kod/object/item/passitem/spelitem/potion/detgoodp.kod
kod/object/item/passitem/spelitem/potion/detinvip.kod
kod/object/item/passitem/spelitem/potion/eageyep.kod
kod/object/item/passitem/spelitem/potion/feigndp.kod
kod/object/item/passitem/spelitem/potion/freeactp.kod
kod/object/item/passitem/spelitem/potion/hastep.kod
kod/object/item/passitem/spelitem/potion/karaholp.kod
kod/object/item/passitem/spelitem/potion/mshieldp.kod
kod/object/item/passitem/spelitem/potion/nightvp.kod
kod/object/item/passitem/spelitem/potion/nodebrsp.kod
kod/object/item/passitem/spelitem/potion/purifyp.kod
kod/object/item/passitem/spelitem/potion/resacidp.kod
kod/object/item/passitem/spelitem/potion/rescoldp.kod
kod/object/item/passitem/spelitem/potion/rescuep.kod
kod/object/item/passitem/spelitem/potion/resfirep.kod
kod/object/item/passitem/spelitem/potion/resmagcp.kod
kod/object/item/passitem/spelitem/potion/respoisp.kod
kod/object/item/passitem/spelitem/potion/resshckp.kod
kod/object/item/passitem/spelitem/potion/rmcursep.kod
kod/object/item/passitem/spelitem/potion/shadowp.kod
kod/object/item/passitem/spelitem/potion/strengtp.kod

This PR updates the descriptions of Potions to include a color descriptor. This is in response to player feedback regarding accessibility and color blindness, which can make some of these potions difficult to visually discern from one another.
In most cases, I used a direct translation of `viColor`.
Mostly direct translations:
> This is a glass vial of blue-colored liquid.
> This is a glass vial of pale blue-colored liquid.
> This is a glass vial of gray-colored liquid.
> This is a glass vial of orange-colored liquid.
> This is a glass vial of red-colored liquid.
> This is a glass vial of purple-colored liquid.
And in other cases, I added my own translations that I felt were in the spirit of the game and make them identifiable:
> This is a glass vial of sand-colored liquid.
> This is a …

Add Potion color to description

---

kod/object/passive/shrine.kod
kod/util/system.kod

This PR adds `RecreateAll` support for shrine allegiance and power level, as requested in #29. To test, I chose two random shrines and dedicated one to Kraanan and the other to Shal'ille, then verified that these dedications and bonuses were accurately recreated on `RecreateAll`. If there's something else I should consider, please let me know!
1. Give yourself the necessary offerings
```
dm get misc
```
1. Check shrine bonuses:
```
send o 0 GetShrineBonus school int 1
send o 0 GetShrineBonus school int 2
send o 0 GetShrineBonus school int 3
send o 0 GetShrineBonus school int 4
send o 0 GetShrineBonus school int 5
send o 0 GetShrineBonus school int 6
```
| 1 | 2 | 3 | 4 | 5 | 6 |
|-|-|-|-|-|-|
| 0 | 0 | 0 | 0 | 0 | 0 |
1. Dedicate shrines
Note: I learned late in testing this that you can …

Adds support for recreating shrines

---

clientd3d/srvrstr.c

Added 5 new text color codes for message use
Colors
Aqua, Lime, Yellow, Pink, Orange
Using the respective prefixes a l y p o
I tested other RBG codes but these stood out the best, some either look too close to the system message purple, or have visibilities issues (too bright or too dark).

feature: update blue and green text colors, add yellow text color option

---

kod/object/item/passitem/weapon/ranged/bow.kod

**Background**
- The current bow.kod uses the standard weapon condition descriptions.
```
weapon_condition_exc = " is in flawless condition."
weapon_condition_exc_mended = " is in excellent condition, but has been repaired before."
weapon_condition_good = " is slightly tarnished but in generally good condition."
weapon_condition_med = " is notched and stained with blood but is still an effective weapon."
weapon_condition_poor = " is well worn and may not last much longer."
weapon_condition_broken = " has been shattered by a powerful blow."
```
**The Problem**
- These do not make sense for **bow** descriptions. A player reported it.
```
weapon_condition_good = " is slightly tarnished but in generally good condition."
weapon_condition_med = " is notched and stained with blood but is still …
```

feature: add bow condition messages

---

kod/object/active/holder/room/temprii.kod

This commit protects the Riija Sword from dropping when unsuccessfully crossing the invisible bridge to the Riija Template (`ke1`). It can still be lost in other ways and this is more a matter of convenience and to minimize the punishment dealt to players using the bridge. Currently, the Riija Sword drops at the bridge and must be retrieved by the player.
Referring to it explicitly felt like the right approach given that implementing `ReqLeaveOwner` or `DropOnDeath` would have had wide-ranging effects on the item outside of crossing the bridge.
To confirm this change, I fell to my death 10 times with a Riija Sword in my inventory and did not lose it. I then added food to my inventory and fell again, that time losing one of my food stacks.

Protects Riija Sword when crossing Riija Temple bridge

---

kod/object/active/holder/nomoveon/battler/player/user.kod

The Problem / Opportunity
- Safety on off messages have a huge impact on the player experience
- The current on-off messages are not as visible as they could be
- Safety On message is currently in italics vs the Safety Off being bold.  It's easier to see if they are both bold.
- With PR#456 merged (brighter colors) we can use them to greater effect with safety on off messages
The Changes
- changed verbose start to very short, capitalized, colored messages "SAFETY ON" vs "your safety is now ON" 
- aligned the text so SAFETY ON and OFF are always in the same position

feature: improved safety on_off messages

---

kod/object/item/passitem/prism.kod

TLDR; prisms sometimes disappear when placed on the floor, this is bad.  This PR fixes that.
Issue
* Prisms are extremely rare items that must be dropped on the floor to use
* They are used during major events such as breaking into a guildhall which may take extended amounts of time
* the DestroyDisposable function will destroy objects in a room including prisms if they are not bonded  (code from room.kod pasted below for reference)
* Given that prisms are one of the only (perhaps only) items that must be dropped on the floor to use, it doesn't make sense they would be at risk of dissapearing due to a room cleanup function
* There is anecdotal evidence of his happening according to chat in the 101 discord where a user said they lost their prism within 3 minutes
The Fix
* return FALSE on …

fix: prevent prism deletion on DestroyDisposable room function call

---

module/merintr/command.c

This commits addresses an issue brought up in #479 where the use of `safetyon` and `safetyoff` displays unintended toggling of the player's safety flag.
Currently, when a player uses these commands they're player flags are updated but their config is not. You can see these by using these commands and looking at your Preferences. Furthermore, there are reproducible steps where unequipping an item can drop your safety and that's not good.
This makes sure that once the player's safety is set, it's persisted to their player and config data.
1. Have no weapon equipped
2. Have "Can attack innocent players" ticbox checked under Game->Preferences [safety is off]
3. Equip a weapon
4. type safetyon command in the text box [safety is now on]
5. unequip the weapon [BUG: safety will now turn off] <-- …

Persists command-driven safety changes to game data

---

kod/object/active/holder/nomoveon/battler/monster/towns/hazartwn/hzapoth.kod
kod/object/active/holder/nomoveon/battler/monster/towns/hazartwn/hzbart.kod
kod/object/active/holder/nomoveon/battler/monster/towns/hazartwn/hzsmith.kod

This is intended to make the newbie experience in Raza a little less spartan by adding items to shops that should be more useful to them while in town.  Complete overview of everything added/changed:
- Raza Smith:  Added small round shield, chain armor.  Removed long sword, scale armor.  The former is a bit of a trap item they can't use properly yet, and the latter is overkill armor.
- Raza Apothecary:  Added mushrooms, blue mushrooms, herbs, elderberries, emeralds, flasks, and torches.  In particular I wanted to make sure most lowbie spell reagents (especially those for touch spells) were covered, and now they are except for a few qor spells (such as acid touch) because they use entroot berries.  The torches and flasks should also prove handy.
- Raza Bartender:  Added green shirt, orange …

Add minor items to Raza's shops

---

kod/object/active/portal/newbport.kod

Currently, exiting Raza sets the player's current vigor to 100 regardless of what it's currently at.  Since players generally leave Raza right after hitting 25 HP, and since gaining a hit point sets your vigor to 200, this is sort of an outdated/weird penalty more than anything else.  This change will bump their current vigor up to 200 (assuming it isn't at or around already) when they exit the Raza portal instead of setting it to 100.,

Raza portal vigor fix

---

blakserv/sprocket.c
clientd3d/client.def
clientd3d/list.c
clientd3d/list.h
clientd3d/protocol.c
clientd3d/protocol.h
include/proto.h
kod/include/protocol.khd
kod/object/active/holder/nomoveon/battler/player/user.kod
module/merintr/inventry.c

Note: cleaned up version of draft PR #462  - had to resubmit because of a complex rebase
Adds
- User can move items with the mouse to sort them as desired
- Backend ability to re-order items in your inventory using MoveListElem from PR #484 
- Paves way for future inventory configuration options (maybe add preconfigured sort commands - group by reagents or alphabetical etc.)
Disclaimer / Notes
- Starting point was skittles1's PR below
- https://github.com/OpenMeridian/Meridian59/pull/964
- Thank to Hektic for helping me resolve some Git issues, and Zaphod for the optimized server side sort function.
Testing / QA
- I haven't seen any issues with this in limited testing
- Code looks sane
- Difficult to test alone in a comprehensive manner compared to production use

feature: sortable inventory

---

clientd3d/list.c
clientd3d/list.h
module/merintr/inventry.c

Implements a more standard interface of move index X to index Y.  Changes the single existing caller (inventory item reordering).

Simplify list_move_item in client.

---

kod/object/passive/spell/persench/karahol.kod

Applying anonymity logic to Karahol; removing the ability for users to "hold" themselves immediately upon re-self cast.

Disallowing Karahol to be re-cast prior to expiration

---

clientd3d/graphics.c

Logical correction to scaling of player overlay equipment when using small game client windows.

Scale player overlay equipment correctly with the Software Renderer

---

kod/object/active/holder/room.kod

This PR fixes #497 by intercepting users, in trances, who have left a room by teleportation. The two specific cases this has in mind are DM teleports and Rescue, which share teleport functionality. The issue prompting this is that Jala casters, wearing Jala necklaces, could Rescue out of a room and leave behind an indefinite room enchantment. In the same way, a DM could also cause this to happen if they cast a room enchantment under the same conditions and teleported away from the room. As result, users would crash or be ask to update their game.

Stops Jala casters from teleporting away from their room enchantments

---

clientd3d/srvrstr.c

Keep classic Blue RBG (  0,  0, 255) as \`b
Keep Cyan but use `c
When I submitted PR #456 I did not realize that the blue color is referenced by monster combat messages and in other help messages (like the initial Raza text blurb when a player joins the game).
The Cyan color is highly visible but clashes a bit with other colors.  Since the monster messages also include red status messages and purple kill messages, it starts to become a bit overwhelming.
I suggest leaving in the classic blue for now, and adding the cyan blue as a communications color option (`c)
Dark blue as  \`b
Cyan blue as `c

feature: keep both blue and cyan blue client text msgs

---

clientd3d/draw3d.c

Restore the original update to `horizon` within UpdateRoom3D as it is used externally by drawbsp.c to determine which objects are visible.

Correct issue with rendered objects disappearing from players vertical view

---

kod/object/active/holder/nomoveon/battler/monster/towns/Goad.kod

Fixed spelling from Goad NPC and in comments.
Slightly adjusted formatting.
No significant changes.

fix: spelling errors and formatting goad.kod

---

clientd3d/draw3d.c

As `params->width` & `params->height` are now always equal to `main_viewport_width` and `main_viewport_height` the divide by 2 operation is incorrect. It turns out that as `DrawBSP` takes the `width` as a parameter but also uses `horizon` and therefore both values need to be correctly updated and so `area` should use the `main_viewport_width` and `main_viewport_height` values directly.
Previously we resolved issues with horizontal objects disappearing from view by avoiding using the use of `area.cx` when drawing the BSP switching to use `main_viewport_width` instead. This was only half of the fix as we should have updated `area.cx` and `area.cy` directly to always be that of `main_viewport_width` and `main_viewport_height`. This change implements this correction and should resolve …

Correction to visible objects area height and width

---

clientd3d/d3drender.c

Rendered objects in the hardware renderer suffers from z-fighting, to prevent this we increase the z-depth for each object drawn.
You could easily spot the z-fighting taking place, such as below:
With this small update we can see many objects without such visual artifacts:

For each object rendered we increase the z-depth to prevent z-fighting

---

module/merintr/stats.c

Whenever the inventory is restored as the active stat group we now ensure that the main game view is the active window.
This includes change also includes an improvement to the interception point and cleaning the code for restoring the active stat group.

Activate main game window when inventory is restored as the active stat group

---

clientd3d/d3drender.c

When a relatively large number of items are rendered in the 3d scene some items (for example the urn in Tos by the GY) would render with an incorrect depth. We now control z-depths by the location of items in the 3d world rather than increasing z depths for each item in the scene.

Control z-depth by the position of each item in the 3D world

---

clientd3d/memmap.c

When using more than one client to play the game you will likely see black square assets in place of the correct images.
With this small change we now enable subsequent open operations on a file or device to request read access.
This issue was due to the share mode preventing other processes from opening files.
https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea

Allow simultaneous read access to game resources

---

kod/util/questengine.kod

Tiny change to game mail subject for Gem Polishing quest failure.

Removing additional space in game mail subject for Gem Polishing quest failure

---

clientd3d/bspload.c
clientd3d/memmap.c
clientd3d/memmap.h

When restoring vision from the blind effect the game world view would often appear to display issues with lighting and other artefacts.
This issue could also cause more severe impact when testing under more extreme conditions - such as creating popup error messages in the client - such messages could appear when running with multiple clients.
Here we make a small switch to obtain simultaneous read rather than write access to a rooms roo file which prevents these issue.
Kudos to m59's Mayhem for helping to identify and resolve this issue :pray:

Prevent graphical lighting and other artefacts when vision is restored from blind

---

kod/object/passive/spell/blink.kod

This PR adds two text messages sent to the user after succeeding in casting blink.  Currently no message is sent and the user's text window simply states the user is concentrating on the spell and the only indication of success is the animation.  This can lead to confusion in cases where you are casting blink often and happen to look away and miss the animation and sound effect.
There are two rooms where you blink and are teleported to a different room as a secret.  These situations now have their own separate success message.

Add blink success message to the user

---

kod/include/blakston.khd
kod/object/item/passitem/numbitem/ammo/firearow.kod
kod/object/item/passitem/numbitem/food/gobletwn.kod
kod/object/item/passitem/numbitem/food/kocmug.kod
kod/object/item/passitem/numbitem/food/mug.kod
kod/object/item/passitem/numbitem/food/soup.kod
kod/object/item/passitem/spelitem/scroll/makefile
kod/util/system.kod

This cleans up some minor grammatical mistakes in a few items, recolors certain stackable foods with duplicate appearances, and adds a scroll that was left out of the makefile:
- mug of stout:  Given a lighter goldish hue to set it apart from mug of brew.  Also expanded its very basic description a bit.
- copper pekonch mugs:  improperly named singular name (copper pekonch mugs) changed to "mug of Pekonch" to match its plural form.  Cleaned up its weirdly-phrased description a bit.
- bowl of soup:  Given a very slight bluish hue to set it apart from bowl of stew.
- goblet of wine:  Changed to a pewter color to set it apart from goblet of ale.
- fire arrow:  Fixed the grammatical mess in its description.  Also properly added it to the item templates.
- scroll makefile:  Added missing …

Very minor fixes and adjustments to items

---

kod/object/item/passitem/defmod/shield/torch.kod
kod/object/passive/spell/mend.kod

The mend spell has a special exception in its logic to exclude the Torch class which is...gross.  I removed it and added an override for CanMend in the Torch class, because mend calls CanMend to determine if an item can be mended or not, not ReqRepair.
Note that this is a nitpick fix that doesn't affect the actual gameplay in any way.

Hackish code for torches in mend fixed

---

kod/object/active/holder/nomoveon/battler/monster/towns/crnthtwn/cngrocer.kod

As a reagent and food vendor, it's expected that Solomon would buy things from players as other similar vendors do, yet he buys nothing.  Although his pricing makes doing so a bad deal, this gives players in Cor Noth an option for offloading reagents and food to him.

Updates Solomon (Cor Noth reagent seller) to buy reagents and food

---

kod/object/item/passitem/defmod/armor/robe/robedisc.kod

This change allows disciple robes to be created in the color matching their school rather than default blue.  It also switches them back to their school color when unequipped.

Updates and polish to disciple robe coloring

---

kod/object/item/passitem/weapon.kod
kod/object/item/passitem/weapon/huntsw.kod
kod/object/item/passitem/weapon/mace.kod
kod/object/item/passitem/weapon/mystswrd.kod
kod/object/item/passitem/weapon/neruswd.kod
kod/object/item/passitem/weapon/riijaswd.kod
kod/object/item/passitem/weapon/scimitar.kod
kod/object/item/passitem/weapon/shrtswrd.kod
kod/object/item/passitem/weapon/spirhamm.kod
kod/object/item/passitem/weapon/unique.kod

Newly-created maces and short swords always show "...but has been repaired before" in their descriptions due to the low quality initial hits modifier being negative, and the repaired-before text displaying if piHits_init is below viHits_init_min, which is possible due to the negative durability value applied to low quality weapons.
While less obvious, high and nerudite quality weapons were shy about showing "has been repaired before" right away because they had an extra buffer of bonus hits before they were considered below the minimum possible durability.
This addresses both issues by removing the quality-based adjustment to piHits and piHits_init done in weapon.kod upon object creation and instead sets the intended values directly in each low, high, and nerudite quality weapon's kod …

Fix for the bugged/inaccurate "has been repaired before" text on low/high/nerudite quality weapons

---

kod/object/active/holder/nomoveon/battler/player.kod

Currently, a player using morph ***or*** illusionary form (and presumably brown potions) can apply the hit side effects (poison, disease, vigor drain, etc) to their attack targets.  Only the morph spell is supposed to be able to do this.
This fix adds a flag check to make sure the user is actually morphed before applying hit side effects, if any.

Bugfix:  Monster hit effects shouldn't be usable via illusionary form

---

kod/object/item/passitem/defmod/pants.kod
kod/object/item/passitem/defmod/pants/shrtskrt.kod
kod/object/item/passitem/defmod/pants/skirt.kod
kod/object/item/passitem/defmod/shirt.kod

As cosmetic items, it's a bit silly that shirts, pants, and skirts take durability damage and eventually break with use.  This leads to people preferring to just hunt naked, or to not bother with these items at all due to the inconvenience of having to pick up new ones regularly.
Removing the durability aspect encourages people to dress up and look their best wherever they go--something they can already do with another cosmetic item:  masks.
This changes the following:
- Shirts (shirt, royalshirt, tanktop) and pants (pantsa, pantsb, pantsc, pantsd, skirt, and shortskirt) to no longer suffer a reduction in hits when the wearer is damaged.
- No longer displays their condition in descriptions.
- No longer mendable, since that doesn't matter anymore.

QoL Feature:  Removed durability damage from shirts, pants, and skirts

---

clientd3d/client.rc
clientd3d/gameuser.c
clientd3d/resource.h

This PR changes the message the player receives when they try to hit themselves with any weapon.  Previously the message the player receives is: "You can't see your selected target."  This is the same message players get often when they are trying to attack a moving enemy or an enemy like ground worms who sometimes dive below the surface of the ground.  This can lead to temporary player confusion as the player often assumes they are targeting the monster only to realize later that they didn't correctly switch away from self-targeting.
In addition, telling the player that they can't attack themselves because they can't see themselves is strange.

Change message when you try to attack yourself

---

clientd3d/d3drender.c

To spawn at the correct position in the 3d world, projectiles include a y offset value. This allows them to spawn at the expected position for example at the middle of a player firing an arrow, or casting a fireball.
These values are perfectly tuned for the original software renderer however the hardware renderer is slightly off in its tuned scaler. For example arrows fired currently spawn at the head of a player. This has both a negative impact when you see a projectile fired from another player and also, from the first person, when it spawns from the top of the screen.
To correct this problem we tune the y-offset scaler for projectiles, reducing from 4 to 3X.
A 4X y-offset scaler is used elsewhere for rendering objects, names and lighting and so perhaps this was the reason this original …

Projectile y offset scaler correction for hardware renderer 

---

kod/object/item/passitem/weapon/ranged.kod

Currently, all bows get the same spellpower modifier of -10 even though each bow tries to define its own modifier.  This is due to weapon.kod trying to define everything based on weapon type.
This fix uses the values defined by each ranged weapon rather than the value weapon.kod assigns to thrusting weapons.

Bugfix:  Spellpower modifier on bows not applying correctly

---

kod/util/nodeattk.kod

This PR adds ~two~ three timer checks to the node attack event.
The first check is made with each new game day that passes. Because the randomness of the timer can be greater than the length of an in-game day, I'm almost certain this logic was adding additional `StartAttackTimers`. We confirmed many of these timers exist on live.
The other timer check occurs when an actual node attack is triggered. In that case, any existing `ptAttack` timer is deleted before being the property is reused for sending player notifications.
Edit: A third check was added for existing servers already dealing with many "bad" StartAttackTimer timers. In that case, disable the event (set pbAttackEnabled=0), wait for these timers to expire, and then re-enable the game.
Ideally, once deployed, this change should …

Fix node attacks by checking for existing `ptAttack` timers

---

kod/object/active/holder/nomoveon/battler/monster/towns/barlqtwn/bqinnk.kod
kod/object/active/holder/nomoveon/battler/monster/towns/kocatwn/kcinnk.kod
kod/object/active/holder/nomoveon/battler/monster/towns/marntwn/mrinnk.kod
kod/object/item/passitem/roomkeyc/roomkey.kod
kod/util/rntmaint.kod

Currently, there's nothing that can be done about a key copy that gets stolen, lost, or just somehow slips away from you.  This adds a command to innkeepers, "change lock" which let you to delete all existing copies of your room key for a particular inn.
As an added note, "change lock" will also allow any "ghost" key copies (copies offered to an innkeeper to be destroyed that don't get disposed because they're still in the master key's plCopies list) to be properly garbage collected.

Rentable room update 2:  Adds "change lock" command to rentable room innkeepers

---

blakserv/adminfn.c

Adds "show exactinstances" as an admin console command.  This is a variant of "show instances" (shows all instances of the specified class) except this version does not include subclass matches.

Adds "show exactinstances" admin command

---

kod/object/item/passitem/ring.kod
kod/object/item/passitem/ring/lethring.kod
kod/object/item/passitem/ring/ringsgnt.kod
kod/object/item/passitem/ring/ringwedd.kod

This PR does a few things related to ring descriptions:
- Adds generral durability condition text to rings' descriptions, if applicable, since currently there's no way to determine how many hits a ring has remaining, short of remembering.
- Fixes a bug where rings with unrevealed item attributes can't have those attributes revealed.
- Changed ring of lethargy to now officially reveals its name/description/color/etc when put on, because it already informally does so the moment a player picks it up.  Until then, it continues to blend in perfectly with beneficial rings.

Minor tweaks to ring description behavior:  added durability, itematt bugfix, ring of lethargy self-reveal

---

kod/object/item/passitem/spelitem/wand.kod

Currently there's no way to keep track of how many charges/hits are left in wands short of one's own memory.  This PR adds durability text to them to help give a general idea of how much they have left.

Durability text for spell wands

---

manual/appa.tex

Fixing a typo in the documentation

Correction to typo in animation details documentation

---

kod/include/blakston.khd
kod/object/active/holder/nomoveon/battler/player/user/dm/admin.kod
kod/object/passive/ornobj.kod

Currently, it's a bit tough and cumbersome for admins to spice up the game with ornamental objects.  This adds a number of features to the OrnamentalObject class to greatly simplify this process:
- DM create ornament:  Adds a dm command to admin.kod and above to place an ornamental object at their current location.
- Adds two signposts to the preset ornament list.
- SetFlickering(value):  Adds a function to allow easier control over an OrnamentalObject's flicker flag.
- SetLookable(value):  Adds a function to set an OrnamentalObject to be viewable with the look command.
- SetCustomDesc(text):  Adds a function to set safe (no dynamic resources) custom descriptions onto OrnamentalObjects.
- ClearCustomDesc():  Adds a function to clear custom descriptions.
- StartDecayTimer(d, h, m, s): …

Admin-friendly QoL changes to OrnamentalObject

---

kod/object/active/holder/room/rentroom.kod
kod/object/item/passitem/roomkeyc.kod
kod/object/item/passitem/roomkeyc/roomkey.kod
kod/util/rntmaint.kod

Currently, the only way users get notified about how much time is left on their room(s) is through a periodic (and somewhat annoying) mail.  This replaced that with the following changes:
- Room key descriptions updated to indicate the number of meridian days remaining.
- RoomKey objects (master/original keys) in particular also show the number of key copies they have in circulation, if any.
- Additionally, room key description generation in general has been cleaned up a bit.  Building all the extra details in DoBaseDesc was probably not how it should've been done since it interferes with added itemattribute descriptions, so now the extra details are built in AppendDesc.
- When a rented room's remaining days value is below a threshold specified in the RentableRoomMaintenance object, the …

Rentable room update 3: Time remaining and other details in key descriptions

---

kod/object/active/holder/nomoveon/battler/player.kod
kod/object/passive/spell/jala/restorat.kod

This PR addresses a gameplay issue where the Jala spell Restorate has no effect for players in the instances where they are most likely to use the spell.  The reason for this is that the HP regeneration rate has a strict lower bound of 1000ms per tick.  Most players reach this lower limit without Restorate being active and therefore the spell has no effect.  For reference: a player with 45 stamina at 100hp or higher hits the limit at 162 vigor.
To solve this problem we lower the lower bound for HP regeneration if the spell Restorate is active.
This solution does create another small gameplay problem: Any reasonable lower limit for HP tick rates makes it so that the maximum effect of the spell tops out at a low spell power.  We solve this problem by reducing the spell power slope and …

Restorate update

---

blakserv/sprocket.c
clientd3d/gameuser.c
clientd3d/object.c
clientd3d/object.h
clientd3d/protocol.c
clientd3d/protocol.h
include/proto.h
kod/include/protocol.khd
kod/object/active/holder/nomoveon/battler/player/user.kod

This PR updates storage boxes like guild hall chests, personal chests in rooms, and other chests that are available throughout the game (IE: Thrashers).
The goal is to make managing inventory easier for players. To that end we make two major changes:
We allow players to pickup a user-selectable number of items for number items
We sort all items in the list box. The sort is two steps: First number items are put at the top and sorted alphabetically then not-number items are sorted alphabetically against each other and appended to the bottom of the list.
This PR differs from draft PR #554 in an important way: We are looping over the list of selected items in C and sending the items to User.Kod one at a time.  This allows the server message to call UserGet and doesn't require a new message in …

Update Containers: Withdraw selectable amount of number items and hierarchical sort

---

kod/object/item/passitem/spelitem.kod
kod/object/item/passitem/spelitem/potion.kod
kod/object/passive/spell.kod
kod/object/passive/spell/purify.kod

Currently, the SpellItem subclasses, particularly potions, have some broken logic that causes them to expend charges vs invalid targets, fail due to karma when karma is flagged to not matter, or even not work at all.
- purify.kod:  Fixed some bad target logic that caused purify potions to fail 100% of the time in all situations when the purify spell was set to self-cast only.
- spell.kod:  Removed a weird check for made items (distill) vs normal potions that was causing normal potions to always consider the user's karma, even when flagged not to (remove curse potion, etc)
- spelitem.kod, potion.kod:  Fixed some buggy logic that caused spellitem charges to be consumed whether or not their effects could be utilized.  (Drinking a remove curse potion without a cursed item equipped, etc)

SpellItem bugfixes

---

kod/object/active/holder.kod
kod/object/active/holder/nomoveon/battler/player/user.kod

The bounding logic for withdrawing shillings from storage boxes results in setting iNumber to -1.  The result was that users can't remove shillings from guild hall chests and other boxes.  Now we set iCan_hold to number in this instance in the same manner we deal with DMs who return NULL for GetNumberCanHold().  The logic is: if the item has no weight and no bulk then we can hold any amount of that item so we set the number we can hold equal to the amount we want to grab and move on.

Fix withdraw shillings from boxes

---

kod/object/active/holder/nomoveon/battler/player/user.kod
kod/util/system.kod

This adds a check for the expiry warning resource (now intended to be a whisper and thus not formatted for user mails) to CleanBadMail in user.kod.  It should allow CleanBadMail to effectively remove all of the invalid innkeeper expiry warning mails while leaving any others untouched.
After being run once and saving, this change can be safely reverted as it will no longer be relevant.
Send o 0 CleanAllBadMail should allow it to run on every single user in one go.
Testing:  I tested this on a character with an invalid expiry mail plus a mail from another user, as well as a mail from the guardian angel--all unread.  It deleted the expiry mail while leaving the others untouched.

Rentable room invalid mail fix

---

clientd3d/d3drender.c

As animation intensity is based on frame rate, the players experience differs.
We use time in milliseconds over frame numbers to correct this variability.

Animation intensity now based on time rather than frame rate

---

clientd3d/graphics.c

This prevents a crash when a large resolution is used that creates a viewport exceeding the maximum supported width.
For example 3840 by 2160 at 100% scale:

Prevent larger resolutions from exceeding the maximum supported width

---

kod/object/item/passitem/roomkeyc.kod
kod/object/item/passitem/roomkeyc/makefile
kod/object/item/passitem/roomkeyc/rmkeysec.kod
kod/object/item/passitem/roomkeyc/roomkey.kod
kod/util/rntmaint.kod
kod/util/system.kod

Silver room keys (key copies) are nice because you can pass them out and share your room with friends, alts, mules, etc, however the risk of losing these keys, either on purpose or accident, exists.
This PR adds an alternate type of key copy option, the bronze room key, which the owner of the room can drop or trade freely, but anyone else cannot drop it, nor can they give it to anyone who isn't the owner or the innkeeper.  
Edit:  Image updated to reflect latest changes

Rentable room update 4:  Secure key copy option

---

kod/object/active/holder/room/monsroom/kcforest/kc4.kod

Long ago, the Origin of the Kriipa map had single-file choke points at the north and south exits that a player could stand in, hold down attack, and just afk-kill enemies as they lined up.  To discourage this, a skill improvement penalty was added.
The map has since been changed to remove these choke points, so this penalty is no longer necessary.

Revert skill improvement penalty in Origin of the Kriipa

---

kod/object/active/holder/room/necarena.kod

This PR adds an isValidTarget message to Necro Arena. 
This message is sent whenever a spell cast is made that requires a target.t and the caster is in an arena.  If the message propagates all the way up to Room.kod the return value is FALSE.  In the two arenas we therefore need some logic to return TRUE if the caster and target are both combatants and if a fight is in session.
This logic was included in Tos Arena but was not included in Necro Arena.  The result is that currently players can not cast attack spells at each other in Goad's Grinder arena.
The IsValidTarget message also relies on GetWatcher.  This PR fixes the necro arena getWatcher message to correctly look for the first instance of the Goad NPC in the room and return that object.  Prior to this change GetWatcher just …

Stepwise Arena Fix - part 1 - Add isValidTarget to Necro Arena and fix GetWatcher implementation

---

kod/util/system.kod

Users remain technically logged in when the server exits.  When it restarts, they're logged out, causing them to leave their room and break any trance.  This sends a message to other objects in the room; however, at this point in server initialization, the room hash table hasn't yet been created, causing error messages.
The hash table initialization was moved earlier so that the tables exist while this logging out process is happening.
Fixes #590.

Fix error messages at startup.

---

kod/object/passive/spell/animate.kod

Removes the DurationSecs parameter animate.kod tries to pass into monster.kod's SetMaster function.  This is a leftover from when zombie.kod had its own version of SetMaster to handle animate's duration via timer, and is no longer relevant.

Remove lingering DurationSecs reference in animate.kod

---

kod/object/passive/spell/shroud.kod

This fixes a bug where the Shroud effect is flagged as unidentified when applied to an item using the Shroud spell.  Since shroud prevents items from also being identified, the identified version of its appended description was never shown under any circumstances short of DM intervention.
Also cleaned up a few minor tab/spacing anomalies nearby.

Fix for shroud's improper appended description

---

kod/kod.mak.linux
kod/makefile.linux

With the recursive makefile structure, a compilation error was
not propagated to outer levels, meaning that kod bugs would
not cause the build to fail.
This does seem to break make -k, however (it will still stop on
the first error).

Linux kod makefiles abort on error

---

kod/object/passive/itematt/weapatt/waench.kod

Removal of an additional space

Remove extra space in Enchant Weapon item description

---

kod/object/item/passitem/defmod/shield/torch.kod

Torches currently use the same durability text as shields, which doesn't make a lot of sense since torches don't shine or get dents, etc.  This PR adds durability text to the torch class that suits it better.
New durability text shown below:

Torch durability text fix

---

kod/object/item/passitem/defmod/armor/robe.kod

Remove an extra full stop :)
This puts it inline with the other items when mended:

Correct mended text for all Robes

---

kod/object/active/holder/room/jasperrm/jaswest.kod

Until this day many a hero has failed to get to safety in Jasper during times of need.
To improve this a small adjustment is made to the placement of the door to Pietro's Wicked Bews. Fixes #647

Correction to coordinates for entering Pietro's Wicked Brews (JasBar) 

---

clientd3d/d3drender.c

Currently players can renderer strangely with other objects in the 3d world.  This is most visible on faction flag poles where soldiers can appear both inside and outside the mast. This also manifests in other ways (such as items appear in-between player bodies).
This change improves the default z bias used and also improves how stacked items z-fighting is managed (by using is gettable).
**Current:**
**With this change:**

Adjustments to render depth defaults for player/non-player

---

kod/object/passive/itematt/weapatt/waexpert.kod

The equations for Colhorr weapons are incorrect. The lack of a +1 on the proficiency value means proficiency maxes out at 99 from the skill, which later leads to a truncation that cuts off a point of damage. This is why Colhorr weapons never 'felt like they did anything' - in many cases they quite literally did not. E.g. +1 damage became +0, +2 became +1. This, combined with the fact that Colhorr weapons actually _subtract_ their bonuses from low proficiency wielders, meant the community simply assumed these don't work at all.

Colhorr weapon att fix

---

kod/include/blakston.khd
kod/object/active/holder/nomoveon/battler/player.kod

I stumbled upon a piece of code in AssessDamage in player.kod that, when a player is damaged, removes a type of paralysis we no longer use, from the old version of Gaze of the Basilisk. There is no other reference to this anywhere else now, meaning PFLAG2_PARALYZED is a player flag that could be used by something else.

Remove defunct Gaze of the Basilisk code

---

blakcomp/blakcomp.l
blakdeco/blakdeco.c
blakserv/adminfn.c
blakserv/apndfile.c
blakserv/async.c
blakserv/blakserv.rc
blakserv/ccode.c
blakserv/channel.c
blakserv/dllist.c
blakserv/game.c
blakserv/interface.c
blakserv/kodbase.c
blakserv/loadall.c
blakserv/loadkod.c
blakserv/loadrsc.c
blakserv/motd.c
blakserv/osd_linux.c
blakserv/roomdata.c
blakserv/saveall.c
blakserv/sendmsg.c
blakserv/session.c
blakserv/string.c
blakserv/synched.c
blakserv/term.c
blakserv/time.c
blakserv/user.c
club/club.c
club/club.h
club/clubarchive.c
common.mak

sprintf will give a warning/error on future versions of the compiler, at least on Linux.  This fixes the easy cases in the Blakod compiler and server, which build on Linux.

Remove most server-side sprintfs.

---

kod/object/passive/spell/distill.kod

The calculation for potion power in Distill uses Max Health, which invisibly lowers your power if you don a circlet, and also allows you to cheese the restriction by morphing into something with high health. Switching to Base Max Health fixes that issue.

Use BaxMaseHealth instead of MaxHealth in Distill calculations

---

kod/object/passive/spell/distill.kod

Set the Go Bad Time for player-made potions to -1 so that they never expire and don't have Go Bad timers.
Formerly, Jala potions never went bad because they are 'labeled,' and the game does not start go bad timers on labeled spell items upon creation. However, the go bad timer could be potentially be restarted if the potion was sold to an NPC and repurchased. Not that such a thing would matter, because the time calculation was also massively off, resulting in go bad times that would have been over a year in length. Jala potions have not had this mechanic for over 20 years at this point, so I figured it's best just to officially set their go bad time to -1. I also don't think it's a good idea to add such a massive number of potential timers to the game, as every single Jala potion would …

Set Jala potions to never expire

---

clientd3d/music.c
kod/object/active/holder/nomoveon/battler/player/user.kod
kod/object/active/holder/room.kod
kod/object/passive/spell/jala.kod

Currently Jala music is bugged such that when a song ends it keeps playing in the room.  Furthermore if the Jala player casts another Jala spell its possible for this bug to crash the client unexpectedly.
This PR aims to fix the issue with persistent Jala music in the hopes that doing so will fix the client crash bug.
To accomplish this goal we make a few minor changes in KOD:
1. Jala.kod was previously used to send a a StartMusic message with a null resource argument.  This was intended to tell the MIDI music handlers to abort the midi file. This has been changed such that EndSpell calls a new message to restart the room music after Jala.
2. The null argument eventually got to MidiSendUser() in User.KOD.  Here however the function just returns if the argument is NULL.  At some point …

Fix persistent Jala music after song ends

---

kod/object/active/holder/room/kocarm/kocinn.kod

This may be an extremely obscure thing to notice, but there is custom text to describe a citizen of Ko'catan in that player's bio.
player_citizen_kocatan = " has lived in Ko'catan"
However, the Aerie Guest House is missing a ROOM_HOMETOWN flag, so anyone who actually becomes a citizen of Ko'catan will lose that hometown if they ever cast rescue, logoff pen, or get sent home by an admin. You cannot currently choose Ko'catan as a hometown in the hall of Genealogy, but it is not impossible for this situation to happen, and also seems like a natural thing that someone might one day add. It's also possible to give this hometown out as an admin event prize or the like.
ROOM_HOMETOWN flags have no extra functionality, and are found in many non-chooseable-hometown rooms, like OOG or Brahma & …

Give The Aerie Guest House a ROOM_HOMETOWN flag

---

kod/object/active/holder/room/rentroom.kod
kod/object/item/passitem/roomkeyc.kod
kod/object/item/passitem/roomkeyc/roomkey.kod

When given to an innkeeper, room key copies are deleted, but not garbage disposed correctly because a reference to the key remains on the master (gold) room key.  These "ghost keys" remain in limbo until the master key is also deleted when the room expires or the change lock command is used.  This provides a simple fix for that.
The following tests were conducted:
- Key copy given to innkeeper to destroy it.
- Key copies bulk-destroyed via the change lock command.
- All keys destroyed upon room expiration.
In every test, a save was performed immediately afterward and the copies were successfully garbage collected without incident.
Note:  This PR is very similar to #630 but with a slightly different approach that doesn't involve sending to an entire key class.

Fix for key copies not disposing correctly.

---

kod/object/active/holder/nomoveon/battler/monster.kod
kod/object/active/holder/nomoveon/battler/player/user.kod
module/merintr/merintr.c
module/merintr/merintr.rc

I was reading this issue with an alternative word for rerolling a character, a more modern game language
https://github.com/Meridian59/Meridian59/issues/660
This change however only adds an alternative command, the old suicide still exists and in some text it still refers to the word "suicide" and "kill youself". Creating this pull request to start a discussion about it, should we keep the suicide command or remove it, shoud we alter any other texts or prompts like this one:

Added a reroll command

---

kod/object/item/passitem/numbitem/food/gobletwn.kod
kod/object/item/passitem/numbitem/food/mug.kod
kod/object/item/passitem/numbitem/food/soup.kod

Not long ago, these items (mug of stout, goblet of wine, and bowl of soup) were recolored to set them apart from items using the same image (mug of brew, goblet of ale, bowl of stew).  After seeing them in game for awhile with their new colors, it's become apparent that this isn't the best way to set them apart from their look-alikes.
This PR restores them to their original colors.  It would still be nice to give these 3 items a distinct look of their own, however it should be done through a unique image rather than recoloring images that weren't set up to use the xlat system in the first place.
Recolors on the left, original colors to be restored on the right.

Revert xlat on mug of stout, goblet of wine, and bowl of soup

---

kod/object/active/holder/nomoveon/battler/monster/towns/crnthtwn/cngrocer.kod

This PR was made in response to issue #628
Originally, Solomon was supposed to accept inky caps, chunks of nerudite, and orc pit boss heads as gifts to elevate his mood.  That doesn't work and hasn't for a long time.  There is also little to nothing affecting his mood actually does, even if the player knows about how it works.
This removes that dead code and adds the orc pit boss head and chunk of nerudite to his willing-to-buy list.  Inky caps are already covered by IsObjectSundry.

Update Solomon's (Cor Noth grocer) willing-to-buy list

---

kod/object/active/holder/nomoveon/battler/monster/towns/tostwn/tswatch.kod
kod/object/active/holder/nomoveon/battler/player.kod

Since reflections and evil twins will soon be functioning in the arena, I got in there and tested them out. Turns out, if you and your opponent are both high karma in the same direction, you will lose the ability to cast Karma-based spells above level 3 after only two reflection kills. Killing reflections in the arena should not affect karma, so I put in a check to prevent that. I put in the broadest prevention possible to shortcut any problems in the future - the Arena isn't real death combat, so Karma should never be changed by actions inside it.

Prevent karma changes in the arena

---

kod/object/item/passitem/defmod/shield/soldshld/prinshld.kod

At low Faction Rank levels, the Princess Soldier Shield is actually *increasing* mana costs by 1. Given that nothing else related to Soldier Shields is ever a negative, this must be an oversight. In this PR, I put a zero bound on it so it will no longer actually make you perform worse.

Zero bound on Princess Soldier Shield mana cost reduction

---

kod/object/item/passitem/defmod/helmet/simphelm.kod

Helmets make you take more damage from bludgeon. Judging by other extremely old resistances being incorrect in the same way, I'm guessing this was a mistake. Flipped it to a positive resistance in this commit.

Flip negative bludgeon resistance on SimpleHelm

---

kod/object/item/passitem/spelitem.kod
kod/object/item/passitem/spelitem/potion.kod
kod/object/passive/spell.kod

In a pervious PR intended to fix potions and karma restrictions, karma  restrictions for all spellitems was unintentionally disabled.   This PR:
- Re-enables karma restrictions for wands and scrolls.  (Potions have it disabled with the exception of the rescue potion)
- Will now properly show text in the description about the item being karma restricted if it is.
- Adds a function/message to spell.kod to query a given spell about its required karma--surprising that this didn't exist already.

Fix for karma-specific spellitems

---

kod/object/item/passitem/manacrys.kod

This PR prevents a Jala singer who is using a Jala necklace from looping Crystallize mana songs.  Now the use of the Crystal will break the singer's trance and end the Crystallize mana song.
EVENT_STEER is used for this purpose to avoid the oddities of EVENT_USE or other events.  This convention is used in other places in the database for ensuring a trance is broken.  A comment to this effect is included in the change.
To test:  Use a Jala Necklace and cast Crystallize mana.  Prior to this change you could consume the mana crystal, leaving the song up.  A new crystal would appear and get filled with the mana that you generated from the first crystal.
After applying this change: Using the crystal breaks the caster's trance and ends the song.  The need for this change was introduced by the …

Consuming a mana crystal breaks the user's trance

---

kod/object/active/holder/nomoveon/battler/player/user.kod

This PR fixes a bug which throws errors to the server when we try to compare an integer to an argument that can be NULL.
The bug had no gameplay effect but is likely spamming the server with these error messages.  The functionality worked prior to this fix because oSplit is already defined before the error is made.
Testing: Use a mortal with a nearly full inventory.  Attempt to pick up a stack of number items.  Note the server error log.  Then incorporate this change and repeat the testing to show that it is fixed.
Additional testing: This logic is also used when withdrawing items from boxes.  I tested with a Mortal withdrawing items that don't fit, where only some fit, and withdrawing items with no weight like shillings.  Everything seems to work.

Fix: User compares an integer to a value from an optional argument

---

kod/object/passive/spell/dishonor.kod

- This changes fixes a server error by modifying the Mark of Dishonor spell to only check if the target has exceeded their natural HP if the target is a player
- Fix for #727 
- The `@GetNewHealth` message call is passed as part of Mark of Dishonor to reduce the HP of a player to their natural maximum.
- The intent is to use this weapon offensively against morphed or otherwise HP-boosted players
- However the logic needed to be adjusted so the `@GetNewHealth` call only occurs for players and not monthers
- Monster classes do not have the `GetNewHealth` message so the server generates an error when it is called
- Moved the `@GetNewHealth` message call to within an existing target check for class `Player`
- Slightly adjusted the comment to specify the check is related to player HP
- No …

fix: mark of dishonor server error messages for monsters

---

kod/object/active/holder/nomoveon/battler/monster/towns/tostwn/tswatch.kod

When a summoned monster gets the final hit in an arena battle we were generating the following error message on the server:
monster.bof (1066)] C_SendMessage OBJECT 6996 CLASS Reflection can't send MESSAGE PostAttackTimer (13444) to non-object 0,0
The monster was finishing its attack logic and then trying to start up its new attack sequence.  Before being able to do so the Tos Watcher was deleting the monsters because the battle was over.  The result is we try to call a message to a nonexistent object.
Converting the two possible delete messages to a Post message prevents this timing error.

Fix: Summoned monsters getting the last kill in arena causes server error.

---

kod/object/item/passitem/instrum.kod

PR #606 allowed the user to equip a weapon or change robes or armor while singing a song if they are using a Jala Necklace.
In the testing for that change it was noted that a user could cast the spell with a Jala Necklace equiped, and then equip a god gift necklace.  Doing so removes the Jala Necklace without calling UserUseItem() or UserApply().  The result was that the player would be able to cast the Jala spell and then put on a different necklace and continue singing.
To fix this potential problem a BreakTrance message was added to NewUnused() in Instrument.  The idea was that every time an instrument is unequipped for any reason the BreakTrance message will trigger the Jala song to end.
In testing prior to having the updates from PR606 going live, it was discovered that a user …

Fix:  Instrument's BreakTrance() message causing server errors with Morph

---

kod/object/item/passitem/roomkeyc.kod
kod/util/rntmaint.kod

This cleans up a few bugs and error messages with room keys and their copies having null RIDs attached to them, most notably when template versions are created through the system function RecreateItemTemplates.
- Attempting to use such a key will delete it back into the void instead of triggering server error messages.
- Attempting to examine such a key will now correctly delete it back into the void.  Previously this wasn't working right.
- The GetMasterKey function on RoomKeyCopy and RoomKeySecureCopy now correctly returns null without generating error messages if either the renter or the room it connects to are null.
- FindKeyByPlayer on RentableRoomMaintenance now correctly returns null if either who or iLocation are null without generating server errors.

Fix for room key and room key copy errors on RecreateItemTemplates

---

clientd3d/client.rc
clientd3d/color.c
clientd3d/color.h
clientd3d/dialog.c
clientd3d/resource.h
include/proto.h
kod/include/blakston.khd
kod/object/item.kod
kod/object/item/passitem/weapon/goldswrd.kod
kod/object/item/passitem/weapon/ranged/bow/magicbow.kod
kod/object/item/passitem/weapon/ranged/bow/nerubow.kod
kod/object/item/passitem/weapon/riijaswd.kod

- several changes based on feedback to calibrate the rarity grade system
- changed MAGIC rarity grade to be UNCOMMON both on server and client
- changed rarity grade logic to add class based rarity `viRarity` and item attributes
- formerly picked the higher value of the two
- changed `viRarity` class based assignment for several items
- removed MAGIC/UNCOMMON from Riija Sword (now is NORMAL)
- moved the following to RARE
- nerudite bow
- magic bow
- gold sword
- changed `item_rarity_grade` enums to be a little more spaced out
- changed LEGENDARY to 4 from 3 so the values line up better with the rarity calculation (mostly just so things are consistent and easier to understand) 
- UNIDENTIFIED is now 100
- CURSED is now 200
``` mermaid
flowchart TD
I(Class Rarity
default = 0)  -->|viRarity| …
```

fix: adjust rarity grade logic to sum (vs bound) and change magic grade to uncommon

---

makefile

- this small change standardizes the command output from the top-level makefile to include the command in the echo output
- previously the `nmake clean` output was inconsistent
- some directories would output `making clean in` whereas others would output `making in`
- reduces ambiguity for contributors (especially inexperienced ones)
- Changed `echo Making in` to `echo Making $(COMMAND) in` on 7 directory calls that did not have the `$(COMMAND`

chore: standardize top-level makefile command output

---

clientd3d/web.c
clientd3d/web.h

- checks and sanitizes URL strings before opening them from the client with a browser
- checks for
- empty URL string
- returns if so
- spaces in the URL
- returns if so
- lack of `HTTP/HTTPS` prefix
- adds `HTTPS://` if there is no prefix
- adds relevant debug messages in client

fix: sanitize target URLs in client before using

---

kod/object/passive/spell.kod

Currently, Qor's 'day and night' primary spellpower bonus calculation does not at all fit the intended theme. It gives the lowest power at midnight, climbing throughout the day (so Qor power is actually really strong mid afternoon) and then peaks at 11 pm, when it then crashes back to minimum at midnight.
This new equation shifts it so that the Qor primary spellpower bonus is strongest at midnight, and weakest at noon. This more accurately ties Qor to 'night time.'
New results:
Midnight - 26 power (maximum)
1 AM - 24 power
2 AM - 22 power
3 AM - 20 power
4 AM - 18 power
5 AM - 16 power
6 AM - 14 power - Dawn
7 AM - 12 power
8 AM - 10 power
9 AM - 8 power
10 AM - 6 power
11 AM - 4 power
12 - high noon 2 power (minimum)
1 PM - 4 power
2 PM - 6 power
3 PM - 8 power
4 PM - 10 power
5 PM - 12 …

Fit Qor primary spellpower bonus to accurately match day/night

---

module/merintr/alias.c

- this change reloads the hotkey aliases into memory after they are saved
- currently players must reload their client for changes in the hotkey aliases "automatic enter" to take effect
- example: players change f1 from `help` to `tg <guild banner>` and uncheck automatic enter
- when they close the hotkey aliases edit screen, it will still automatically enter
- the only workaround is to restart the client
- it's a small quality of life change but I think will be welcomed by players
- today while on 101 someone was complaining about this issue after telling a guildmate to log on and off for their aliases to be updated properly
- created new function `UpdateKeyTables` to update saved in-memory key configuration
- used by both `AliasInit` and `AliasSave`

fix: make hotkey aliases refresh without restarting client 

---

kod/object/passive/itematt/iashroud.kod

- this change makes reveal and identify work on the `IA_SHROUD` item attribute
- when shroud is cast by a player, the `IA_SHROUD` item attribute is added as an identified attribute
- however, in some cases an admin can manually add the `IA_SHROUD` item attribute to an item as an unidentified attribute
- with the new rarity grade system these items show up in the client as `UNIDENTIFIED`
- this change "fixes" the issue by allowing players to reveal and identify shrouded items
- since `IA_SHROUD` does have a unique description string, it should be identifiable or reveal-able
- > A cloak of magic surrounds it.
- in limited testing I was able to reveal and identify items with the `IA_SHROUD` attribute that were applied before this change
- no errors seen in the server log
- there is another …

fix: make reveal and identify work on shrouded items (IA_SHROUD)

---

clientd3d/config.c
clientd3d/statgame.c

This change reintroduces the original sleep used to lower CPU load while the game is running in the background which was previously [removed](https://github.com/Meridian59/Meridian59/pull/452).
In addition to this change we now also improve app background detection for sleeping, reduce maximum frame rate of 120 FPS and finally prevent the animation timer triggering on non game screens (was happening on at least the character selection window).
A background sleep of 1ms quickly produces a 0% cpu when the game is in the background without significant game activity (such as numerous hostile monsters animating). Using a value of 0ms does not achieve 0% cpu and actually *significantly* raised background CPU usage due returning immediately …

Reinstate animation sleep to lower CPU load while in background

---

clientd3d/d3drender.c

Correct the ui scaling when in gpu efficiency mode
becomes:

Correctly scale ui elements in gpu efficiency mode

---

kod/object/passive/spell/dishonor.kod

There were multiple issues in Mark of Dishonor that are fixed in this change
- removed an unused string resource
- made spell work even if the target player has positive karma
- it used to consume resources on the caster but not cast on the target due to returning false if karma > 0
- adjusted monster behavior
- previously it would try and adjust the behavior to ignore the caster but had no effect (monsters would continue attacking even though the code was trying to make them stop attacking)
- now enrages the target monster and causes them to attack the caster (makes more sense I think)
- added a vague string regarding the target appearing lethargic if the spell successfully punishes the target player's vigor
- > X appears more lethargic.
- the spell would fail when casted on any positive …

fix: multiple Mark of Dishonor issues

---

kod/object/active/holder/nomoveon/battler/player/user/dm/admin.kod
kod/object/item.kod

This PR causes item attributes added through the "dm create itematt <attribute>" command to always be revealed.  Previously, an admin using this command would have to use the reveal spell, which is problematic if one of the added attributes was shroud.
If the old behavior of adding an unrevealed attribute is preferred, the command "dm create unrevealed itematt <attribute>" has been added.

Fix for DM-added attributes not being revealed

---

kod/object/active/holder/nomoveon/battler/player/user/dm/admin.kod

Currently an admin can unintentionally issue certain dm commands if they say specific keywords in their regular, everyday speech, such as "mortal."  This PR adds a check to make sure the commands are properly issued through the dm command channel.
Subsequent, redundant checks for SAY_DM on certain commands have also been removed.

Fix for certain admin commands being triggered by normal speech

---

clientd3d/d3drender.c

Logoff ghosts were being rendered as if they were invisible - this small change prevents that.

Restore logoff ghosts visuals

---

clientd3d/d3ddriver.c
clientd3d/d3drender.c

Updates to the 3d hardware graphics to improve a few long standing issues, including: borders around Barloque archway doors, sign posts, and the cobwebs in cv basement. This also prevents small lines appearing around some of the smaller moon phases.
We add separate sweeps for translucent and opaque world objects and rework the rendering states throughout.
**These changes should to be fully beta tested before being released to ensure its working across a range of setups and configurations by a number of different users.** 
Please note north bq room requires an [update to fix another issue](https://github.com/Meridian59/Meridian59/pull/789) to see it like this:
also here (north bq room update required)

Dedicated passes for transparent world objects with render state rework

---

clientd3d/game.c
kod/object/passive/viewglbe.kod

This PR seeks to resolve an issue seen in the Lich maze (`lichmaze`) when using the globes/cameras. When a player uses a globe their viewpoint becomes the top of the globe and is above the height of the ceiling, causing a visual bug. This PR uses `REMOTE_VIEW_BOTTOM` instead of `REMOTE_VIEW_BOTTOM` to set their viewpoint to the bottom of the globe, rather than the top.
https://github.com/Meridian59/Meridian59/assets/467443/5266cb8c-55e2-4f49-9ed1-e8b044b67a03
https://github.com/Meridian59/Meridian59/assets/467443/e6db9d5e-0510-4c0c-a728-5c964b18f043

Adjust the viewing height of ViewpointGlobe's so as not to be affected by ceilings

---

module/mailnews/newsread.c

This PR came about from some comments in #798:
> It might be a good idea to show a down arrow on the Date column when the dialog loads, to indicate the default sort order. Also, if you initially click on the Date column, nothing happens, You have to click twice.
While addressing that feedback, I realized that rescanning and posting new messages introduce new, unsorted items to the list. This PR addresses all of these things by sorting by descending date when articles are first presented, rescanned, and when new articles are posted.

Sorting enhancements for newsglobes

---

clientd3d/msgfiltr.c
clientd3d/ownerdrw.c
clientd3d/ownerdrw.h

- this change attempts to make wholist handling more robust to reduce client crashes related to `DrawOwnerListItem`
| function | line | filename|
| - | - | - |
`meridian!DrawOwnerListItem` | 377 | ownerdrw.c
`meridian!OwnerListDrawItem`  | 288 | ownerdrw.c
`meridian!WhoDialogProc` | 153 | msgfiltr.c
- there are several bug reports on different dates related to a crash in `DrawOwnerListItem` on this line
```
if (style & (OD_DRAWOBJ | OD_DRAWICON) && obj != NULL)
item_rarity_value = (item_rarity_grade)obj->rarity;
```
- It is suspected that the compiler might be reordering things within the `DrawOwnerListItem` function
- if so, this line could be the culprit (as pointed out to me)
- [Meridian59/clientd3d/ownerdrw.c](https://github.com/Meridian59/Meridian59/blob/bf65a1a5677e277379662456ca42f9 …

fix: make colored listbox text more robust in client

---

module/mailnews/mailread.c
module/mailnews/newsread.c

This PR reformats `mailread.c` and `newsread.c` using `clang-format`'s default Visual Studio formatting style. This is partly to tidy up, but also to make working with them easier as I look to apply the sorting logic from news to mail.

Reformats `mailread.c` and `newsread.c` classes

---

kod/util/library.kod

Rodric is the first NPC's new player's encounter and is accompanied by a tutorial sign directing the user to say "HELLO" to get a reaction. The only problem is, Rodric doesn't have a trigger or response for this command. This adds a simple greeting in response to a player saying "hello".
> Ah, greetings, adventurer!  May your journey be filled with fortune and glory.
- A recreate() call on Library is needed to rebuild the library with this new response.
This PR closes #610.

Adds 'hello' response for Rodric d'Stane

---

kod/object/passive/spell/multicst/hunt.kod

This PR disables Hunt. When used on offline targets who log on during it's duration, the target will be tracked indefinitely. Offline players' timers are "frozen" by `FreezeAllEnchantments()` and converted into integer times, but Hunt introduces an active Timer that decouples from the enchantment during reactivation of enchantments in `ReactivateAllEnchantments()`. This should be addressed or the spell reworked before re-enabling.

Disables Hunt until it's implementation issues are resolved

---

clientd3d/map.c

This PR makes two changes to the map:
1. It makes the player map marker static in size rather than based on the player width, which causes the current player marker to scale with map zoom. Today's map marker and player direction are almost indistinguishable when zoomed out or when the player zones into larger rooms. This PR uses a new `MAP_PLAYER_MARKER_SIZE` macro to draw and maintain a statically sized marker.
2. Map objects like monsters and other players are static, but perhaps a tad too small. This PR increases the thickness of these markers/dots by 1.
Here are screenshots showing 3 levels of zoom with these changes in effect:
I believe this PR closes #744 
Note: I removed the unused `MAP_PLAYER_FRONT_COLOR` macro and commented out use of it.

Statically size the player map marker

---

.gitignore

This PR adds a new ignore for the temporary `filename.roo~` files created by room edit.

Adds ignore for temporary roomedit files (`room.roo~`) to gitignore

---

clientd3d/login.c

Checking account activation is relatively slow - we now only do it after three failed login attempts.

Only check for account activation after 3 failed logins

---

module/char/charpick.c

Recently found instances where new characters are not listed at the end of the character selection screen:
This change uses std::sort and the outcome here being:

Sort characters names alphabetically with new users at the end

---

kod/object/passive/spell/creasphm.kod

Add the word hammer to the text that happens when you cannot hold a spiritual hammer.

Add missing word in Spiritual Hammer spell

---

clientd3d/d3drender.c
clientd3d/server.c

If a player is blinded and something changes in the scene (for example a monster is killed) then later when blind wears off the geometry hasn't been updated and we see missing textures. We reinstate the trigger to redraw all from `HandleChange`. Please see PR commit history for an[ alternative solution within 3d3render only](https://github.com/Meridian59/Meridian59/pull/907/commits/1c51b578f3211345dda5adf5bba7ec7aeeb64923).
Issue:
https://github.com/user-attachments/assets/fa4208d5-0852-4461-899c-deb6f6784869
with changes:
https://github.com/user-attachments/assets/3e3cdaed-644b-4ac4-a883-c41723a7a64d
Fixes #908

Redraw all in hardware renderer as blind wears off

---

clientd3d/d3drender.c

We apply the same techniques for overlays as for regular objects (only render each object once and restrict translucent passes)
Logoff ghosts now look consistently translucent (previously overlays -- arms, legs etc were rendered twice and at certain distances were rendered multiple times due to duplication in drawdata)

Single render pass for translucent overlays

---

clientd3d/draw3d.c
clientd3d/graphics.c
clientd3d/overlay.c

Full screen mode of the software renderer does not currently scale using the classic resolution and FOV. The FOV is calculated by the height and width defined within the draw room routine which we are setting with the height and width available. This is wrong as it also increases the view port and FOV significantly, above and beyond the original classic client view (and the hardware renderer). Instead we now improve the software renderer full screen implementation by scaling the classic view to the size of the available view port area -- importantly keeping the original scale and FOV.
Current full screen view:
With this new classic stretched implementation (this is large full screen max):
Scaled from original smaller ~classic view port size (this is a small view):

Stretch classic software renderer with classic original scale and fov

---

kod/object/active/holder/room/monsroom/kcforest/ke4.kod

Per @jrotunda's suggestion in #471, this PR adds two new monster generator locations along the ridge often used by players to grind while avoiding monster engagement. This PR codifies a change already in place on 101.
Closes #471

Adds two new monster generator locations to Avar Village (`ke4`)

---

clientd3d/d3drender.c
clientd3d/draw3d.c

In busier rooms (number of items/lights/walls) and at higher resolutions the number of draw items may exceed the maximum allowed. On further investigation the greater the resolution, the greater the number of items being identified as visible in the world - which is wrong. This spawns from the original implementation of the full screen for software renderer: https://github.com/Meridian59/Meridian59/pull/911
When this happens out of memory messages would appear in the debug logs as the `drawdata` was full and as a result objects were missing and not rendered in the 3d world.
As the world is being built from the bsp tree using a static world size and the width is given as a parameter - regardless of the screen resolution the same objects in the world should be visible. This width of the …

Adjust FOV for hardware renderer to match classic software renderer

---

clientd3d/d3drender.c
clientd3d/graphics.c

During https://github.com/Meridian59/Meridian59/pull/911 we assume all `TranslateToRoom`'s are being stretched from classic width/height. This is not the case for the hardware renderer, so we correct it for both cases.

Make objects clickable in the hardware renderer

---

clientd3d/d3drender.c

Check for null pRNode before use

Prevent projectile crash

---

kod/object/active/holder/nomoveon/battler/player.kod
kod/object/active/logghost.kod

Logoff ghosts currently do not display overlays (such as masks or helms) - we add that functionality.

Make logoff ghost overlays visible

---

kod/object/active/holder/room/temprii.kod
kod/util/system.kod

In response to #625, this PR adds a broadcast to all currently logged in users when a player unsuccessfully crosses the Riija bridge. It uses `GetTrueName`, so there's no hiding from the shaming.
> `### PlayerName just hurled hisself from the cliffs of Riija to find a watery grave.`
Closes #625

Adds folly broadcast to Riija bridge deaths

---

kod/object/passive/quest.kod

This PR updates the quest health requirement (`Q_R2_HAS_HEALTH_LEVEL`) to look at the player's unmodified base max health instead of their modified max health, which is affected by the likes of circlets and spells. These effects will no longer cause the faction leaders (the only uses of this requirement right now) to ignore players seeking the 'soldier' quest.
Fixes #739

Check unmodified base max health for faction soldier quest requirements

---

kod/object/active/holder/nomoveon/battler/player.kod

This PR addresses one of the issues brought up in #491 in which NPCs responses to skills can be confusing. As it stands, when an NPC is asked about a skill (e.g. a player curious about their progress) they first check to see if a players current skills meet or exceed the necessary level. For example, a player asking for a level 1 spell when they're already working level 2. The code returns there and responds that the player is ready. However, it can be the case that a player already has the skill they're asking about and _that_ check isn't reached. This can be confusing and it seems to me the response for a skill already learned should always be _the skill has already been learned_.
So, this PR does a quick loop through spells and skills and triggers the more appropriate response before …

Performs "already learned" check on skill asks of NPCs

---

clientd3d/d3drender_skybox.c

During deconstruction of the skybox we did a small refactor for `D3DRenderBackgroundSet` https://github.com/Meridian59/Meridian59/pull/928. This wasn't correct as the previous code uses a `strstr` We update the code to cater for this. 
Tested by switching successfully through times of the day `send o 0 sethour num int 21`.
After prompting also tested with a frenzy `send object 0 StartChaosNight` successfully with hard coded asset names.

Correctly select skybox assets

---

kod/object/active/holder/nomoveon/battler/player.kod

When a player joins a faction, `FactionServiceTimer()` creates a timer callback to itself to determine faction status and if good, create another timer to do the same in the future. The problem seen in the logs, is that when control returns to this method, the reference to the timer remains but the timer has since been deleted. The result is a `DeleteTimer()` error.
I'm unable to pinpoint a point in the code where an inadvertent deletion of this timer exists and am kind of assuming that when the timer expires and the call to `FactionServiceTimer()` is made, the timer has been cleaned up and the reference via `ptFactionTimer` remains.
To fix this, I've removed any timer deletion code from `FactionServiceTimer()` and have given that responsibility to `FactionServiceRoutine()`.
Testing this …

Fixes erroring faction service timer deletion

---

kod/object/passive/itematt/weapatt/waparal.kod

This further avoids traditional spell cast logic by flagging this weapatt's spell cast as an item cast via `bItemCast`. Doing so avoids a few bits of traditional spell casting code in Spell's `CastSpell()`. 
In Discord, I had suggested that without this flag the player might be improving off a weapon attribute. However, an instance of `self` (the weapon attribute) is being passed to `CastSpell()`, standing in as the caster, and causes `ImproveAbility()` to return immediately.

Adds `bItemCast=TRUE` flag to Hold weapatt spell cast

---

kod/object/passive/itematt/weapatt/wapurge.kod
kod/object/passive/spell/purge.kod

This PR plays the purge spell audio cue on successful hits. It does so by going through `CastSpell`, as `waparal.kod` does.
```
Your weapon tears at the magic surrounding Test3.
Your axe slashes Test3.
```
```
Test1's weapon tears at the magic surrounding you!
The spirit of battle has left you.
Test1 slashes you with his axe.
```
In my testing, purge often failed to remove a single PE because of the randomness of it. However, I only wanted to address the audio and not get into the probability of its effectiveness.
Fixes #820

Adds purge audio to purge weapon hits

---

kod/object/passive/spell/seduce.kod

This PR fixes #461 by verifying that the target monster is still alive during each iteration of Seduce's mana drain timer. Currently, if an affected mob is killed, `EndEnchantmentTimer` doesn't recognize this and the mana drain continues until the caster is out of mana. Additionally, it performs new checks to ensure the master (player) is present.
**About Seduce**: When cast on a monster, seduce will cause the monster to fight on your behalf for as long as your mana allows. If your mana runs out, the monster turns on you. Seduce can be cast on multiple monsters. If a monster is killed, the mana drain (from that monster) should stop.

Seduce: Verify conditions before continuing enchantment

---

kod/object/active/holder/room/monsroom/f7.kod

This PR adds a looping sound to the room with a source location of the northern stream.
**Note:** I'm unable to test this locally as the fallback WaveMix audio driver doesn't support radius and volume.
Fixes #621

Adds looping water sound to stream in Off the beaten path (`f7`)

---

kod/object/active/holder/nomoveon/battler/monster/towns/barlqtwn/bqinnk.kod
kod/object/active/holder/nomoveon/battler/monster/towns/kocatwn/kcinnk.kod
kod/object/active/holder/nomoveon/battler/monster/towns/marntwn/mrinnk.kod
kod/util/rntmaint.kod

This PR adds the following improvements to the "room cost" command and its functionality:
- Adds an underline to the various room rental keywords to make them pop better.
- Adds text for the newer commands: "secure" keyword for copying keys, as well as the "change lock" command.
- Added an alternative command to reach the "room cost" dialog:  "room help" which seems like something a player is more likely to say when they want to know the commands and such.

Update to innkeeper room cost command

---

kod/object/active/holder/nomoveon/battler/player.kod
kod/object/passive/spell.kod

This PR adds logic to skip skill and spell improvement room audio cues (added some time ago) when the improving player is a hidden admin.
This is in response to and fixes #819

Remove hidden admin imp audio cue

---

kod/object/active/flag.kod
kod/util/factgame/territry.kod

This PR modifies the `SetFaction` function to only change the flag's faction without performing post-processing steps. Specifically, the flag claim process and other related actions will no longer occur when only the faction is updated. This is needed to properly recreate the territory game and specifically, the full version of the territory game.
* I manually converted flags to another faction when testing. Using `send o <TerritoryGame> GetFlagCounts` to verify the counts were the expected values.
* Tested existing functionality to ensure no side effects or unintended behaviors were introduced when recreating the territory game and when performing a system `RecreateAll`.
* This has been attempted and discussed before in #450 
* This attempts to address the issue with the least change …

Fixes territory game recreate by skipping post-processing on flag claims

---

clientd3d/map.c

This PR is meant to address some feedback heard on #809. Currently, other player's markers (blue dots) can sometimes be tiny in comparison to the player's marker and difficult to spot. This PR increases the size of them by introducing new pen so that _the_ player and other players can be styled differently. To help identity yourself against others, this PR also updates the player's marker to cyan.
I've also heard some concerns about situations where many players are in close proximity to one another. While there are situations and zoom levels where players dot will mash together, it would seem uncommon for those dots to remain static.
I created some representative examples of the current state vs what's proposed in this PR by screenshotting, copying, and pasting player markers. If there …

Revises map marker sizing and color

---

kod/object/item/passitem/ring/besring.kod

This PR is an alternative to #658. Currently, when ranged weapons are used in tandem with a berserker ring, the ring's durability will decreases even though it's damage buff does not apply to ranged weapons. This will remove the invisible effect of ranged weapons on the ring's durability. It _also_ replaces some magic numbers. I can revert if preferred.

Remove ranged weapons' impact on berserker ring durability 

---

kod/object/active/holder/nomoveon/battler/monster/eviltwin.kod
kod/object/active/holder/nomoveon/battler/monster/reflectn.kod

This PR sets the karma of reflections and evil twins to 0, rather than the caster's karma. This came about from a discussion in Discord, where it was felt that killing illusions should not impact player karma.
This was also the subject of #535.

Remove karma from reflection and evil twin

---

clientd3d/annotate.c
clientd3d/annotate.h
clientd3d/map.c

This PR introduces improvements to how map objects and annotations are scaled during zoom operations. The changes are meant to ensure that both objects and annotations are constrained in a way that offers proper visibility and prevents scaling issues at various zoom levels and in the various room sizes.
https://github.com/user-attachments/assets/d48e6432-91b7-4861-a56c-d57237c719ec
https://github.com/user-attachments/assets/3d9f08ee-ac6d-4611-aeab-52cc52a7ebc9
https://github.com/user-attachments/assets/ac849105-be9a-4077-a2e8-492d72df7ffd

Puts a cap on map object and annotation sizes

---

.vscode/settings.json

This PR adds a Visual Studio Code settings file to the project that enforces `windows1252` encoding for `rc` files.
Currently, contributors must manually reopen `rc` files with the correct encoding before saving to avoid introducing unwanted characters, especially in files containing translations. This settings file automates the process, ensuring `rc` files always use the proper encoding, preventing encoding errors and preserving file integrity.
Windows-1252 supports ISO-8859-1 plus full support for the following ligature forms (for English):
* German
* Portuguese
* Spanish
* French
* and [more](https://en.wikipedia.org/wiki/Windows-1252)

Adds vscode settings file with encoding settings

---

clientd3d/d3drender_objects.c

We remove unwanted alpha blending around world objects but filling and flushing the cache between opaque and transparent passes.
Tested that transparency is still functioning correctly for monsters and overlays.

Prevent unwanted alpha blending of objects

---

keybind/Assignkey.cpp

This commit is pretty straightforward. I was looking at the mouse config and noticed that these values could be converted to their predefined constants.

Updates mouse x-button assignment to use predefined constants

---

kod/object/item/passitem/attmod/frozjewl.kod
kod/object/item/passitem/specwand.kod

This PR serves two purposes - to remove the clutter that inevitably clogs inventories when using wands, or Jewels of Froz; and bringing consistency to the way that consumable combat items are disposed of.
Both wands and Froz remove delete themselves after depletion, like Berserker Rings.  The "shatters" message for wands already makes perfect sense, but the Froz depletion message was updated to be more accurate and lore friendly.

Quality of Life: Auto-delete depleted wands and Froz

---

kod/object/active/holder/nomoveon/battler/player/user.kod
kod/object/passive/moon.kod
kod/object/passive/sun.kod

Currently, background objects are only sent to players on login. When a system save takes place they disappear from the room overlays and are therefore not rendered (in both hardware/software renderer). This could have never worked or been supported by the game until now.
This change adds them again following a system save as well as on login.
fixes https://github.com/Meridian59/Meridian59/issues/990

Add background objects following a system save 

---

clientd3d/graphics.c

Adjusting translate to room to fix issue: #996 `view.x` and `view.y` should not be included in these checks - tested with hardware / software renderer where this function returns false

Adjust viewport bounds for checks for translate to room

---

clientd3d/d3drender_objects.c

This prevents z-fighting that may appear between monsters, players and monsters and single item stacks.

Add z-depth adjustments for all objects at the same location

---

clientd3d/client.c

This PR introduces mouse wheel support for zooming in and out of the map, making navigation a bit more intuitive and user-friendly. Users can now use their mouse to zoom both the map view and minimap.
https://github.com/user-attachments/assets/da80de59-45ea-4aee-961a-cf898f2738e5

Adds window capture of mouse wheel to zoom map

---

clientd3d/d3drender_objects.c

Reports that being invisible while a translucent monster (such as a slime) caused the player is not be visible at all.
Translucent, invisible morphed players will now be visible.

Make world object invisible checks consistent

---

clientd3d/d3drender_objects.c

Incorrectly set `bHotspot` value during deconstruction - needs to default to false not true.
This was causing incorrect rendering issues when another player had some equipment and used magic.
Also remove a useless comment that was added previously
https://github.com/Meridian59/Meridian59/pull/916/files#diff-006128dfe5afe1d5b5b42cb04abcb98e0b6c96c74c3e4c6ab70fd3177cb9021cL7447

Correction to bHotspot default value

---

clientd3d/client.rc
clientd3d/config.c
clientd3d/config.h
clientd3d/download.c
clientd3d/resource.h

Using the built-in updater for Steam installs results in a broken installation.
Fixes #748.

Direct Steam users to Steam for updates

---

clientd3d/d3drender.c
clientd3d/server.c

When we solved visual issues when a player recovers from blind https://github.com/Meridian59/Meridian59/pull/907 we introduced a new issue than can cause flicking textures on some screens.
We revert that change and install the alternative solution that was provided in the original PR to solve the recovery from blind issues and solve the new flickering texture issue.

Prevent flicking of textures

---

clientd3d/d3drender_bgoverlays.c
clientd3d/d3drender_skybox.c
clientd3d/d3drender_world.c

We have some unwanted blending taking place between static world geometry and the skybox. This issue is most obvious at certain times of the day when the sky is bright on screens such as the outskirts of Barloque or the Flatlands.
To solve this we correct when and where alpha blending is enabled/disabled.
Before:
After:

Adjust alpha enablement to prevent unwanted blending world edges

---

kod/object/active/holder/nomoveon/battler/player/user.kod

Toko detected an error in the logs following https://github.com/Meridian59/Meridian59/pull/992/
```
[user.bof (2241)] SendBlakodMessage can't propagate MESSAGE SendBackgroundObjects (14377) in CLASS User (1)
```
We correct this by returning rather than propagating in SengBackgroundObjects.

Correctly return from SengBackgroundObjects

---

clientd3d/d3drender_bgoverlays.h
clientd3d/d3drender_objects.h

`d3dRect` contained nonsense values, causing bad calculations for visible area calculations, preventing background overlays from being clickable. We fix `d3dRect` in render bgoverlays and also optimize `driverProfile` in render objects.

Correction to render parameters

---

clientd3d/bspload.c
clientd3d/d3drender.c

During https://github.com/Meridian59/Meridian59/pull/950/ `SandstormInit` from `BSPRooFileLoad`. 
`SandstormInit` should be called only once per room. Therefore its new location in `D3DRenderBegin` isn't suitable as it can be called more than once per room and this will stop the effect from displaying.
We return back to its original position to ensure sandstorm is visually functioning correctly.
There also appears to be visual bug with sandstorm on the live game. 
The good news is that that issue appears to be resolved with the latest on github.

Persist sandstorm effects

---

kod/object/passive/trestype/avart.kod
kod/object/passive/trestype/skel2t.kod
kod/object/passive/trestype/skel3t.kod
kod/object/passive/trestype/skel4t.kod

This PR addresses an issue where certain monsters drop too many unstackable items.  As these items build up on the ground, graphical glitches such as flickering or vanishing/invisible objects occur after only a few minutes due to the number of unique objects on the screen.  The only current remedy is to leave the room and reset it every few minutes.
This addresses that issue by making the unstackable items much rarer, or removing them in some cases, then padding the table with stackable items that are typically of lesser value.
The drop rates of each monster's "valuable" stackable items is preserved, so I don't expect much of an economic impact.
Monsters affected:
Avar
- Added:  uncut seraphym, turkey leg
- Removed:  purify potion, cure poison potion, cure disease potion (all sold by lady …

Updated treasure tables of certain "messy" monsters

---

module/mailnews/mailread.c

Patch 1.4 introduced mail sorting, which relies on the system locale for parsing. After release, exceptions were reported, likely due to the user's system not supporting the specified locale. This PR adds a fallback: if setting the locale fails, the client catches the issue and falls back to the "C" locale. Before implementing this change, I tested by forcing a bad locale (e.g., setting `localeName` to `bad_locale`), which previously caused the client to crash. With the fallback in place, the crash is avoided, and English mail is parsed correctly using the default locale.
My theory is that the new support for Portuguese (Brazil) may have introduced a mismatch with standard Portuguese (non-Brazilian) or another unexpected locale configuration, triggering this issue.
A limitation of this …

Adds catch for invalid or unavailable locale in mailread

---

kod/object/passive/itematt/weapatt/waspellt.kod

This PR addresses an issue with DM-added weapon attributes of the spell attack type. Currently, when these attributes are added via `dm create itematt holy`, for example, a timer is not provided. It's needed by a later check and its absence causes the errors seen in #1007.
These weapon attributes are randomly generated with a duration of 1-24 hours. For the DM version, I chose 24-hours as anything created by a god ought to last a while.
I also snuck in a small change to the spell type descriptions that get appended for consistency with all other text formatting.
* `dm get item mace`
* Equip the mace
* `dm create itematt holy`
* Examine the mace to verify it's enchanted with a holy attack
* Verify the error logs are clear of issues
This fixes #1007

Adds 24-hour duration to DM-added weapon spell attributes

---

kod/object/passive/statue.kod
kod/util/system.kod

After we added the ability to show overlays on statues: https://github.com/Meridian59/Meridian59/pull/927
We found out that any existing statues that had overlays that were created before this upgrade would have a mismatch between the number of calculated overlays and the overlays sent to the client. We create a one time upgrade to solve this, fixing any existing statues that need to be recalibrated.
Testing:
Created a server pre-upgrade and reset the statues and saved the game state. Upgraded post https://github.com/Meridian59/Meridian59/pull/927 - got the bug and then ran this fix, saw the one time upgrade applied to all statues and the bug was gone.

Upgrade existing statues

---

module/mailnews/mailfile.c

This fixes a critical issue where mail subject handling was incorrectly tied to the number of recipients.
Previously, the subject line could be written in the wrong position. If there were more than three recipients, the client would crash.
To resolve this, I adjusted the logic by tracking the subject ID separately.
This supports blank subjects, which appeared to be a problem when this bug surfaced.

Fixes mail subject handling tied to recipient count

---

kod/object/item/passitem/gift.kod
kod/object/item/passitem/spcgift2.kod
kod/object/item/passitem/specgift.kod

- added `unwrap.wav` sound to `specialgift.kod` and `specialgift2.kod`
- in #975 I didn't include two gift classes because I didn't realize there were others
- as a result two types of gifts did not make the gift unwrap sound
- no errors in server log or client debug window when opening any of the 3 gift classes
- no errors on build
- sound works for all 3 gift classes now

fix: add unwrap sound to all gift classes

---

kod/object/item/passitem/prism.kod

- fixed small typo in `prism.kod`
- "miniture" to "miniature"
- > If you peer closely you can see a **miniature** landscape
- tiny fixes add up over time

fix: small typo in prism.kod

---

clientd3d/d3drender_bgoverlays.c

Adjust the texture coordinates (s and t) of the vertices of a background overlay to mirror the texture on the x-axis.
Since [rotating the backgrounds](https://github.com/Meridian59/Meridian59/pull/1016) to match the origin image orientations, the background objects were no longer clickable. To prevent this, we revert the change and instead we swap the s coordinates of the vertices. The background objects are once again clickable.
before:
after:
Fixes: #1039

Mirror background textures on the x-axis

---

kod/util/questengine.kod

This PR is another small change aimed at improving the questing experience by decreasing the default quest retry time from 4 hours to 1 hour. Note: It's currently 20 minutes on 101.
This aims to ease issues raised in #491

Decreases time between quest retries

---

kod/include/blakston.khd
kod/util/questengine.kod

This PR introduces a new quest for Parrin that lets players earn a Jala insignia for their herald shield. The quest is modeled after the priestess insignia quests, requiring players to collect Jala-inspired items, and includes messaging that reflects Parrin’s distinct personality.
Currently, the Jala insignia is unintentionally very rare, only obtainable through the CV crate at extremely low odds. Even if this rarity wasn’t intentional, it created an unnecessary barrier for players. From what I understand, the original intent was to make this insignia available through gameplay, and this update helps fulfill that goal.
Closes #712

Adds new quest for Jala shield insignia quest

---

kod/object/item.kod
kod/object/item/passitem/ring.kod
kod/object/item/passitem/ring/lethring.kod
kod/object/item/passitem/spelitem/wand.kod
kod/object/passive/spell/identify.kod
kod/object/passive/spell/reveal.kod

This PR addresses issue #702, where Identify wasn’t revealing item name and description as expected. To address this, I added code to Identify that will temporarily reveal an items hidden attributes, then hide them once again. I took this a step further by also revealing and hidden an items hidden color, if it has one. Examples of this include many of the magical rings.
With this fix, Identify now works as intended _and_ will (temporarily) reveal an item's hidden color.
1. Screenshot of an item with hidden attributes, including color:
2. The same item when Identify is cast upon it, revealing it's true name, true description, and hidden color, but only temporarily in the dialog:
3. If the user inspects the item again, any attributes that were hidden will be hidden once again:
4. And if a …

Adds additional Identify functionality around hidden attributes

---

kod/object/item/passitem/gift.kod
kod/object/item/passitem/spcgift2.kod
kod/object/item/passitem/specgift.kod

This PR removes redundant calls to `LeaveHold` for gift classes (`Gift`, `SpecialGift`, and `SpecialGiftTwo`). These items are already flagged as single-use types and are automatically removed from the player's inventory, so the explicit `LeaveHold` call is unnecessary. These redundant calls were triggering a client debug message about a non-existent item in the player's inventory.  
To reproduce the issue, these gift classes can be distributed to all users using the following commands:  
```
send o 0 globalgive number int 1 classtype c Gift
send o 0 globalgive number int 1 classtype c SpecialGift
send o 0 globalgive number int 1 classtype c SpecialGiftTwo
```  
Testing included monitoring object counts before and after opening the items and garbage collection. This was done by deleting …

fix: Remove redundant `LeaveHold` calls for gifts as single-use items

---

kod/object/active/holder/nomoveon/battler/player/user.kod

PR 722 fixed a common cause of server errors but inadvertently prevented the user_got_some message from being sent to players when they pick up item stacks off the ground but can't hold the entire stack of number items.
I tested:
-Mortal user picking up a stack they can't hold all of from the ground - no errors
-Mortal user removing a stack they can't hold all of from a chest - no errors
The actual code change is one line - a long comment describes the three possible options for the comparison / conditional statement.

Restore User_Got_Some message to players when number argument is null

---

kod/object/active/holder/nomoveon/battler/monster/towns/kocatwn/kcbowmak.kod

Hanla zax'Ta has a conditional sale of Kriipa claws - however it is currently broken.
We add the conditional seller attribute `MOB_COND_SELLER` that will enable this functionality. The `MOB_COND_SELLER ` attribute is required for the seller to have their `InitCondSale` called, enabling any conditional sales (via monster Constructor or library ReInitialize)
Will require a `send o 0 RecreateAll` from server side to enable from an existing setup.

Add conditional seller attribute to Hanla zax'Ta

---

kod/object/active/holder/room.kod
kod/object/passive/spell/multicst/shadrift.kod

This commit adds `NO_COMBAT` rooms to the list of rooms excluded from shadow rift portals. Previously, only the `HISTORIC` rooms were excluded. This commit also moves the logic checking this to `CanPayCosts()`, so that the user gets immediate feedback that it cannot be cast.
`NO_COMBAT` rooms include:
- Inns
- Taverns
- Adventurer Halls
- Raza
- Many of the NPC/town rooms (blacksmiths, the vault, banks, etc)
- The Clearing of the Trading Post, Outside the Mad Scientist's Hut, The Remote Trading Post of Wulfgang zax'Ak, and a few others
- Rented Rooms

Denies Shadow Rift in `NO_COMBAT` rooms

---

kod/object/active/holder/nomoveon/battler/monster/towns/decoratr.kod
kod/object/active/holder/room/rentroom.kod

This PR updates object placement in rented rooms to align the object's orientation with the player's facing direction. This change primarily affects multi-sided objects, such as the personal chest. The decorator's dialog has been updated to reflect this.
The decorator says this when placing an object is requested, **bolded** text is newly added:
> Please stand where you'd like the object, **look in the direction it should face,** and say 'here'."
Fixes #646

feature: Adds directional placement to rented room objects

---

resource/graphics/makefile

This PR removes the mollusk BGF from the compilation process. Since we no longer compile this file (see #903), it’s unnecessary and is currently triggering an error message. 
```
...
Building graphics
Unable to load bitmap file mol000ug.bmp
NMAKE : fatal error U1077: '..\..\bin\makebgf.EXE' : return code '0x1'
```

fix: Removes mollusk from graphics makefile

---

kod/object/active/holder/nomoveon/battler/monster.kod

This PR increases the NPC spam timer range from 40-60 seconds to 2-5 minutes to reduce noise and improve the pacing of messages (or actions, like emotes). I tweaked the delay range calculations to ensure they fit this new span.

world: Increase NPC spam timer to reduce message frequency

---

kod/object/active/holder/nomoveon/battler/monster/towns/jasprtwn/jsmerch.kod
kod/object/item/passitem/numbitem/food/watrskin.kod

This PR adjusts the `piNumber` value for waterskins to align better with other food items, making them more suitable for monster treasure drops.
It has been adjusted from 20 to 2, consistent with similar food items.
* **Zombies:** Now drop 2 waterskins instead of 20.
* **Zhieu B'hob:** Now starts with a quantity of 4 waterskins instead of 20 for sale.
* Send `SetForSale` to Zhieu B'hob to update his item list

feature: Revised waterskin `piNumber` to modify availability

---

blakserv/interface.c

- makes MOTD pop-up dialog box appear centered on the `blakserv` application window on Windows
- modifies `CenterWindow` function in`blakserv` Windows application
- adds support for multiple monitors
- #608 fixed issues with the Meridian 59 client, this adds similar fixes to the Meridian 59 `blakserv` application
- Fixes the MOTD dialog box appearing on the wrong screen 
- for example, screen 1 has the application but the MOTD dialog box will open on screen 2
- The "Are you sure you want to exit?" dialog box will appear on the correct monitor, but centered on the desktop not the application
- I looked into fixing this, but that message box is a system-managed dialog box which is difficult to modify
- I tried a few workarounds but since it does open on the correct monitor, it seems ok
- I …

fix: MOTD `CenterWindow` function in `blakserv` win interface

---

dlg/dialog.txt

- regenerates `dlg\dialog.txt` after spelling corrections took effect on `dlg\npc.tab` in #1061 
- the spelling corrections implemented in #1061 applied to `npc.tab` 
- in order for the changes to apply to a M59 server, the `dialog.txt` file must be regenerated by the `dlg\dialogconvert.py` script (done by this PR).
- also contains some encoding fixes for `dialog.txt` that were applied to `npc.tab`

chore: regenerate `dlg\dialog.txt` from `dlg\npc.tab`

---

kod/object/item/passitem/chalice.kod

The Chalice was adjusted back in 2013 to allow all players (not just non-angled) to partake. However, it was changed to prevent all outlaw/red characters from using it instead. As per original follow up discussions in 2013: we correct the use of the Chalice to make it fair and consistent with rescue/elusion: https://github.com/Meridian59/Meridian59/pull/37#issuecomment-13698080
This brings a level playing field to the use of the chalice for all.
testing:
Confirmed working as expected when used on local server. Unable to chalice away and see new message until timer condition is met.

Make the Chalice of the rain function like rescue and elusion

---

clientd3d/dialog.c

This PR adds `IDC_APPLY` to the set of controls that are repositioned when the object description dialog is resized, such as when using non-default fonts. Previously, `IDC_APPLY` was not included and remained stationary, which appears to have been an oversight rather than an intentional choice.
Here is an example of what happens today:
And once updated:
Closes #1028

fix: Properly move `IDC_APPLY` control when description dialog is resized

---

kod/object/active/holder/room.kod
kod/object/active/holder/room/rentroom/kocrent.kod

There is a bug with the new rentable rooms in kocatan, if you cast rescue when in a rented room it sends you to your hometown on mainland instead of The Aerie Guest House, this is because this room is not treated as a RID_KOCATAN.
The problem is that rentable rooms are not using piRoom_num (they do not have a room number) and you cannot distinguish a mainland room from a kocatan room.

Fix rescue bug in kocatan rentable rooms

---

kod/object/passive/itematt/weapatt/waparal.kod

Typo in comments, was blind, is now hold
Stumbled across this when I was looking at weaponatt

Fixed a typo in comments

---

kod/include/blakston.khd
kod/object/active/holder/nomoveon/battler/monster/frogman.kod
kod/object/passive/trestype/frogmant.kod
kod/object/passive/trestype/makefile
kod/util/system.kod

This PR revisits the Frogman treasure table after #758 (credit to @Gar103), making adjustments based on the discussion in that PR to give the Frogman a unique treasure table—without, hopefully, any controversial changes.
Per past discussions, the Frogman should roughly align with Skeletons, who fall are a mid-range target for good karma players. The Frogman is a target for evil-aligned players and offers reagents that make sense in that regard.
Item | Drop Rate (%)
-- | --
Blue Mushroom | 24%
Mushroom | 24%
Elder Berry | 24%
Entroot Berry | 9%
Purple Mushroom | 9%
Dark Angel Feather | 5%
Inky Cap | 4%
Magic Shield Potion | 1%
Closes #466

feature: Adds a unique treasure table for Frogman

---

kod/object/item/passitem/chalice.kod

Old messages when the chalice was used, empty or refilled said "Chalice of Rain", the name is "Chalice of THE Rain", now updated and added "THE".

Fix: Typo in Chalice of the Rain messages

---

kod/object/active/holder/nomoveon/battler/player.kod
kod/object/passive/spell/focus.kod

Many years ago a changed was added to the spell mana focus, it was supposed to make mana focus increase mana regen, but it has never worked because the spellpower was never recieved.
The code in player.kod:
**iTime = Send(oSpell,@AdjustManaTime,#who=self,#time=iTime);**
the _old_ code in focus.kod:
**AdjustManaTime(time=0, iSpellPower=0)**

Fix: Mana focus to give mana regen

---

kod/object/active/holder/room/barlqrm/barapoth.kod

This PR adds three braziers to Joguer's—two that were clearly meant to be there but were missing, and a third that was commented out. The room has two flickering light sectors that weren’t properly matched with light sources, and the third brazier adds a nice touch behind the counter.

fix: Revises the placement of braziers in Joguer's (`barapoth`)

---

kod/object/active/holder/room/monsroom/objroom/cave2.kod

This updates the light level of Icky Cave from `LIGHT_DARK` to `LIGHT_MIN`.
In the codebase:
- `LIGHT_MIN` is used for caves, sewers, and Brax.
- `LIGHT_VERY_DARK` is used for areas where darkness is desired but not extreme (e.g., boss rooms like the throne room, orc pit, lupogg king lair, lich maze, and deep forests).
- `LIGHT_DARK` is used for spaces with high walls, forests, or "spooky" areas like Castle Victoria and the graveyard.
Given these conventions, `LIGHT_MIN` is a better fit for Icky Cave and other cave rooms.
Related to #1108

feature: Decrease Icky's base light level to be consistent with caves

---

kod/util/questengine.kod

Over time, monsters' `plActiveQuestNodes` lists have been observed to accumulate more quest nodes than expected. This appears to be related to the QuestEngine's `Jumpstart()` functionality, which recreates quests but doesn't properly clean up existing quest nodes from monsters.
This PR makes the following changes:
* Modifies the `ClearAllQuests()` function to remove all quest nodes from every monster.
* Renames `Jumpstart()` to `Reset()` and integrates the updated `ClearAllQuests()` within this new function to ensure that quest data is fully reset.
* Navigate to an NPC like the Princess in `castle2c`.
* Observe the plActiveQuestNodes list. It should start with several nodes and accumulate additional ones with each quest engine cycle.
* Run the new Reset() function on the quest engine.
* …

fix: Quest node accumulation on monsters (NPCs)

---

blakserv/adminfn.c

A missing "R" parameter in an admin command used to go off the end of the command string.  Now it generates an empty parameter.
Fixes #1135.

Fix parsing of admin command for "R" parameters.

---

blakserv/adminfn.c

This delays kicking sessions off until after everyone has left the game.
Fixes #1146.

Check for users in game before "reload game".

---

kod/object/active/holder.kod
kod/object/active/holder/nomoveon/battler/monster.kod

Currently, murderers cannot purchase from lawful NPCs when DMs are present in the room (even hidden DMs), as DMs are counted as fellow customers. This creates unintended interference with normal gameplay.
This PR adds the ability to exclude specific classes (like DMs) when counting objects in a holder. By updating the lawful NPC checks to ignore DMs present in the room, DMs will no longer be counted as fellow customers and murderers can go about their business.
- Verify murderers can purchase from lawful NPCs when:
- No other players are present (only DMs)
- DMs are hidden in the room
- DMs are visible in the room
- Verify existing behavior remains unchanged when:
- Regular players are present
- No DMs are present
Fixes #1140

Add class exclusion list to `Holder::CountHoldingHowMany` and exclude DMs from customer list

---

kod/object/active/holder/nomoveon/battler/monster/towns/barlqtwn/assassin.kod
kod/object/active/holder/nomoveon/battler/monster/towns/kocatwn/kcmerch.kod

This PR reduces the purchase prices offered by Roq and Wulfgang from (`EXPENSIVE`) 60% to (`RIPOFF`) 50% of item value, because their unique ability to purchase any item type warrants a more conservative pricing structure.
A small example of the change in action:
Current `EXPENSIVE` offer:
Updated `RIPOFF` offer:
Closes #1125

change: Reduces purchase prices for unrestricted merchant NPCs (Roq and Wulfgang)

---

kod/object/active/holder/room/jasperrm/jaswest.kod

The existing door texture spans two coordinates, but only one was set as an entry point. This makes entering the tavern frustrating at times. This PR simply adds a second coordinate to fully cover the visual width of the door, making entry more intuitive.

qol: Adds an additional entry point for the Jasper tavern door

---

kod/object/active/holder/nomoveon/battler/player.kod
kod/object/active/logghost.kod

This PR fixes a loop issue in the logoff ghost's item dropping logic when dropping everything.
**Bug Example**
With 1 droppable item in inventory:
1. `iNumItemsInventory = 1`
2. First iteration: `i = 1`, drop succeeds
3. `i` stays at 1 (we don't increment on successful drops)
4. Second iteration: `i = 1 <= iNumItemsInventory (1)` is true
5. Try to drop item at index 1 again, but inventory is empty
On the server side, an error will be thrown from `Player::FindItemByIndex`, as there is no longer an item at index 1.

fix: fixes item dropping logic in logoff ghost

---

clientd3d/annotate.c
clientd3d/buy.c
clientd3d/client.def
clientd3d/color.c
clientd3d/dialog.c
clientd3d/dialog.h
clientd3d/lookdlg.c
clientd3d/msgbox.c
clientd3d/say.c
clientd3d/tooltip.c
clientd3d/transfer.c
module/admin/admindlg.c
module/mailnews/mailread.c
module/mailnews/newsread.c
module/mailnews/newssend.c

This PR introduces a couple of improvements to map annotations behavior:
1. **Annotations and tooltips are now fully disabled if either "Show dynamic minimap" or "Map annotations" is turned off.** 
One could argue there's some benefit to having them display, but I think it's more confusing to have tooltips appear for annotations the player can't see.
2. **Tooltips are now properly cleared when many dialogs are displayed.** 
I added a wrapper around `DialogBoxParam` that calls an updated `TooltipReset()` beforehand. This helps clear lingering tooltips before most dialogs appear. I skipped a few dialogs that likely don’t interact with tooltips.
I recorded this video to show a variety of conditions under these changes:
- Players cannot create or edit map annotations, or see their tooltips, …

fix: Improvements to map annotations and tooltips

---

kod/util/questengine.kod

This PR fixes #711 by adding responses to the NPCs involved in the Qor, Faren, and Shal'ille disciple quests. Each of these quests asks the player to say a specific line to another NPC. Right now, those NPCs stay silent, which makes it unclear if the player did the right thing or should return to the quest giver. This adds a simple response to help communicate that.
Each group of NPCs uses a shared line that reflects their alignment and tone. The Qor targets are good-aligned and reject the message outright. The Faren targets are being chastised and respond with dismissal. And in the Shal'ille quest, the targets reject the player’s offer of peace and sends them back with a cold dismissal.
This should help players move through these quests with a bit more clarity.

feat: Add NPC responses to guide disciple quest progression

---

clientd3d/signup.c

Previously, non-ASCII characters (e.g., ó) were being silently replaced with visually similar ASCII characters (e.g., ó replaced by regular o) by the signup form itself, which could be especially problematic for fields like passwords. This PR introduces validation to detect and reject invalid characters, rather than silently replacing them, ensuring users are explicitly informed of the issue.
Additionally:
- "Select all" functionality has been added to applicable fields.
- Fields left empty will now trigger clear, field-specific error messages instead of the generic "sign-up failed" message previously shown.

Disallow invalid username and password characters during signup

---

clientd3d/buy.c

The changes made in [#565](https://github.com/Meridian59/Meridian59/pull/565) have made organization in rooms and guild halls a far smoother experience - this PR applies the same hierarchical sort to the 'buy' and 'withdraw' boxes so it can be enjoyed by those who frequent vault-men and NPC merchants alike. 
Code-wise the changes are very straight-forward; it applies the algorithm introduced by @CardiovascularMike in #565 > `GotObjectContents`.
This PR was tested on every NPC willing to make sales in Barloque, as well as Obert with both the 'buy' and 'withdraw' commands.

Apply hierarchical sort to buy & withdraw lists for consistent UX

---

clientd3d/preferences.c

Fixes these problems:
- Toggling music pref has no immediate effect.
- Turning off sound pref doesn't cancel existing sounds.
- Changing music volume has no immediate effect.
- Options menu not updated when music/sound toggles changed.

Fix bugs with prefs and music/sound

---

blakserv/adminfn.c

This proposed fix doesn't work given what strtok does. Ideally we would use std::string instead of strtok for argument parsing.

Roll back #1144 as it was losing R admin parameters

---

kod/object/active/listener.kod

Eavesdrop's Listener object calls the wrong function when attempting to name someone leaving. As a result, it simply sends no message. Like SomethingEntered just above, it should call ReportNameToTarget.

Fix incorrect function call in Eavesdrop's Listener

---

blakserv/chanbuf.h
blakserv/interface.c

- adds safety checks when displaying `listbox` item text to prevent stack overflow and handle invalid selections
- increases interface buffer size by using established channel constant `CHANBUF_SIZE`
- fixes #1258
- previously, the function directly called `ListBox_GetText` with the result of `ListBox_GetCurSel` without error checking
- this could cause buffer overflow on very long messages or undefined behavior if no item was selected
- the changed version validates the selection index and ensures the retrieved text length fits safely within the buffer
- changed static 400 byte interface buffer size to use `channel.c`  constant `CHANBUF_SIZE` (currently 1000 bytes)
- added `LB_ERR` checks for `ListBox_GetCurSel` and `ListBox_GetTextLen`
- displays a warning dialog if a message exceeds …

fix: address Windows blakserv dialog crashes

---

kod/object/active/holder/nomoveon/battler/player.kod

- adds educational messages to prompt players to change rooms when they hit the current room advancement cap for skills and spells
- this change provides informational messages only and leaves the improvement system and caps as they are
- players currently hit the 10-point advancement limit and continue casting spells/practicing skills without knowing why they can't improve, wasting reagents and money for 15-22 minutes until the timer resets
- the existing anti-botting system reduces advancement points by 2 when players change rooms, but this mechanic is hidden from players, leading to frustration and resource waste
- many veteran players DO know about this dynamic and have an advantage over those that don't; it's an open secret
- the intent of the advancement limit was to prompt players …

feat: add improvement cap prompts when player hits cap
