kod/object/active/holder/nomoveon/battler/monster/nrthlwrm.kod
Fixes Death sounf of Nathryl Worms
=> Fix for Nathryl Worm Death Sound

kod/object/item/passitem/defmod/shield/guilshld.kod
Till now Jala Heralds dont give Spellpower like the others
=> fix jala spellpower on heralds

blakserv/makefile.linux, blakserv/mutex_linux.c, blakserv/session.c, rules.mak.linux
- libs need to be at end to link properly
- mutex needs to be released before being closed
- mkdir needs -p to not whine
- linux server looks pretty good after this
=> fix up blakserv makefile, mutex for linux

blakserv/synched.c
Fixed a sizeof statement that was using the wrong value.
=> Fix sizeof statement.

blakserv/async.c
- fixed some bad line endings in async.c too by editor
=> fix linux build to set sockets non-blocking

clientd3d/client.rc, clientd3d/login.c, clientd3d/resource.h
- The new screens/resources
- Also includes a small adjustment to one of the resource definition names (homepage->signup)
2 of 4
=> Signup resources

clientd3d/client.h, clientd3d/web.c, clientd3d/web.h
- Adding SendHttpsRequest to web.h/c
3 of 4
=> Secure web request

kod/object/active/holder/storebox/woodbox.kod
giving more reason to steal guild halls since they can have more fat sacks of l00t
=> Guild Hall wooden chest

kod/object/active/holder/storebox/chest.kod
Just feel like you should have fat sacks of loot in guild halls and people would want to steal them more.
=> Guild Hall metal chest

kod/object/active/holder/nomoveon/battler/player.kod
coded by theanax
Added an additional point to gain on kill and on kill with taking damage that should effectively up the HP gain rate a bit.
Changed the newbie bonus XP to scale with whatever the angel setting is rather then stopping at 25.
=> Small XP gain changes

kod/object/passive/skill/secwind.kod
This commit returns where a propagation error was being thrown.
=> Fixes propagation error

clientd3d/d3drender.c, clientd3d/draw3d.c
Minor adjustment to FOV calculations to cater for all client window sizes.
Resolves: #463
=> Prevent objects vanishing from view after manually resizing the client

module/chess/board.c, module/chess/cmove.c
After the previous change for flipping the board vertically for Black, the layout of the board was actually incorrect.
=> Fix layout of chess board

clientd3d/client.rc
Update signup dialog text for server descriptions to make consistent with the website.
=> Update signup dialog text for server description

contrib/powershell/Monitor-Room-Resources.ps1
This PR adds a Powershell script to `contrib/` that will detect new and modified .roo files in `/resource/rooms` and copy them to the localclient resources in real-time. A huge click-saver when editing room files.
=> Adds PowerShell script to detect and copy updated .roo files to localclient

clientd3d/login.c
Do not check account status when not using retail flows
=> Skip account verification status check when not in retail mode

kod/object/item/passitem/spelitem/scroll/darkscrl.kod, kod/object/item/passitem/spelitem/scroll/discscrl.kod, kod/object/item/passitem/spelitem/scroll/disilscl.kod, kod/object/item/passitem/spelitem/scroll/earthscl.kod, kod/object/item/passitem/spelitem/scroll/firitscl.kod, kod/object/item/passitem/spelitem/scroll/flashscl.kod, kod/object/item/passitem/spelitem/scroll/heatscrl.kod, kod/object/item/passitem/spelitem/scroll/killfscl.kod, kod/object/item/passitem/spelitem/scroll/lghtscrl.kod, kod/object/item/passitem/spelitem/scroll/mrtrscrl.kod, kod/object/item/passitem/spelitem/scroll/pfogscrl.kod, kod/object/item/passitem/spelitem/scroll/sporescl.kod, kod/object/item/passitem/spelitem/scroll/windscrl.kod
Set the correct school graphics for scrolls, per Mayhem's issue.
However, the Kraanan icon changes color with the scroll. Maybe that's not a huge issue, or we could try to find some other solution for that.
=> Set correct graphics for scrolls

clientd3d/client.rc, clientd3d/signup.c, clientd3d/web.c
Also fix signup URLs when client is in German.
Also fix some grammar in messages.
=> Fix spurious error dialog when creating account.

aws/src/server_process/server_process.py
Improve `send_command`, logging and timeouts.
=> Aws game server script improvements

aws/src/daily_cleanup/app.py, aws/template.yaml
Use s3 bucket policies to expire account files and create temporary audit
=> Aws account archive and auto-delete policies

aws/src/daily_cleanup/app.py
Append new accounts to the main database file
=> Aws update database with new account entries

aws/src/daily_cleanup/app.py
Removing  redundant `accounts_to_delete` and multiple checks to the database.
=> Improve daily aws clean up job

clientd3d/d3drender.c
Reinstate translucent effects (shadow beast / slimes) in the hardware renderer.
This change also prevents translucent objects (or any object) from being rendered twice. This would manifest as a slight visible reduction of translucency from certain distances. This change also supports improved translucency as previously you couldn't see other world objects at times behind a translucent object and now this should generally work correctly (second screenshot was not possible in the past)
Resolves: #738
=> Reinstate translucent effects in hardware renderer

clientd3d/d3drender.c, clientd3d/graphics.c
Add a check during rendering for a valid player.
resolves #771
=> Check for valid player during rendering

clientd3d/d3ddriver.c
Improve quality with [multisample support](https://learn.microsoft.com/en-us/windows/win32/direct3d9/d3dmultisample-type)
=> Add multi-sample support to d3d driver

clientd3d/d3drender_objects.c
Adding required externals that were removed during deconstruction review
=> Restore view and projection for invisible objects

clientd3d/d3drender.c, clientd3d/d3drender.h, clientd3d/d3drender_skybox.c
Small clean/tidy up of particles, removing unused/multiple definitions
=> Deconstruction small cleanup

kod/object/active/holder/room/monsroom/bossroom/sewking.kod
This is formatting cleanup in preparation for work in this kod.
=> Formatting cleanup for `sewking.kod`

kod/object/item/passitem/defmod/shield/soldshld/prinshld.kod, kod/object/passive/spell.kod
This PR modifies the Princess faction's shield bonus (mana reduction) to be a percentage based on rank, ranging from a 5-25% reduction in mana costs. As seen in #735, the shield bonus for Princess soldiers is poor in comparison to the other factions; many of her faction levels offer NO bonus. Currently, the bonus maxes out at a savings of -2 mana per cast. With this change, the savings are a percentage of the cost and are detailed below.
I'd like to note that my formulas are maybe more verbose than they could be, but I thought it was important to show the values involved.
| piFactionRank | Mana Cost Reduction (Current) | Mana Cost Reduction (Proposed) |
|---------------|------------|-----------|
| 1             | 0          | 5%         |
| 2             | 0          | 7%         |
| 3 …
=> Updates Princess shield mana reduction bonus to be %-based

clientd3d/d3drender.c, clientd3d/d3drender.h, clientd3d/d3drender_objects.c, clientd3d/d3drender_objects.h, clientd3d/d3drender_world.c
Removing externs from render objects using several new structures.
Just refactoring, no changes to the game or rendering expected.
=> Remove render objects externs

clientd3d/d3drender.c, clientd3d/d3drender_objects.c, clientd3d/d3drender_objects.h, clientd3d/d3drender_world.h
Removing player extern from d3drender.
Just refactoring, no changes to the game or rendering expected.
=> Removal of player extern from d3drender

kod/object/item/passitem/attmod/frozjewl.kod, kod/object/item/passitem/specwand.kod
Reverts Meridian59/Meridian59#983
=> Revert "Quality of Life: Auto-delete depleted wands and Froz"

blakserv/saveall.c, blakserv/savegame.c
=> handle errors in saving in the server better

clientd3d/d3drender.c, clientd3d/d3drender_fx.c, clientd3d/d3drender_fx.h, clientd3d/d3drender_objects.c
Removing externs from render FX using several new structures.
Just refactoring, no changes to the game or rendering expected.
=> Removal of render FX externs

clientd3d/d3drender_bgoverlays.c
Rotate background assets to match expected visuals
=> Rotate background overlays

kod/object/active/holder.kod, kod/object/active/holder/nomoveon/battler/player.kod, kod/object/item/passitem/warlettr.kod
- fixed multiple typos in 3 .kod files
- most of these typos are related to player game mails they receive
- it makes the game look better
=> fix: multiple typos in kod files (holder, player, warlettr)

kod/util/assgame.kod
Add some help to players who enter a non-viable assassins game
fixes: #1047
=> Inform player when the assassins game is not viable

kod/object/active/holder/nomoveon/battler/monster/towns/kocatwn/kcbowmak.kod
Add a welcome message for Hanla zax'Ta
=> Add a welcome message for Hanla zax'Ta

aws/src/reset_password/app.py
Ensure password reset request goes to the websites failure page when something goes wrong.
=> Improve password reset failures and logs

kod/object/item/passitem/numbitem/food/watrskin.kod
This PR is nothing more than a few style changes.
=> Small style reformat

kod/object/active/holder/nomoveon/battler/monster/towns/marntwn/mrinnk.kod
This PR updates Morrigan's room rented message to avoid any confusion that might come from directing players to Tova.
> Here ya go then.  Hope you enjoy your stay, if you have any problems Tova will be glad to help you.
> Here you go then.  Hope you enjoy your stay!  If you run into any troubles, you know where to find me.
Closes #1070
=> change: revises Morrigan's room rented message to remove any confusion

kod/object/passive/spell/multicst/shadrift.kod
Formatting improvements to Shadow Rift's kod.
=> format: Reformats `shadrift.kod`

kod/util/questengine.kod
add the better user experience from shal/faren quests to the qor quest
=> Add quotes to Qor disciple quest message

.clang-format, clientd3d/bsp.h, clientd3d/bspload.c, clientd3d/d3drender_world.c, clientd3d/drawbsp.c, clientd3d/roomanim.c, clientd3d/roomanim.h
This applies the new clang formatting rules (#1168) to a handful of files to clean things up before making further changes. Let me know if there's anything about these rules we’d want to tweak based on how this turned out.
=> format: clang formatting of several files, updated clang-format rules

clientd3d/mapfile.c, clientd3d/mapfile.h
This may speed up room transitions a little bit.
=> Use buffered I/O for mapfile
